// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
#include "counter_node/diagnostics.hpp"

#include <chrono>

namespace demo {

CounterNodeDiagnostics::CounterNodeDiagnostics(rclcpp::Node & node, CounterNodeEngine & engine)
    : node_(node), engine_(engine) {
  group_ = node_.create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);

  pub_ = node_.create_publisher<diagnostic_msgs::msg::DiagnosticArray>(
      names::kDiagnosticsTopic, rclcpp::QoS(names::kDiagnosticsQosDepth));

  timer_ = binding::create_timer(
      node_, clock_, std::chrono::seconds(names::kDiagnosticsPeriodS), [this]() { drain(); },
      group_);
}

void CounterNodeDiagnostics::drain() {
  using diagnostic_msgs::msg::DiagnosticStatus;

  diagnostic_msgs::msg::DiagnosticArray array;

  engine_.drain_diagnostics([&](r2d::Code code, const char * who) {
    DiagnosticStatus status;
    status.level = code == r2d::Code::ERR_RUN_101 ? DiagnosticStatus::ERROR
                                                  : DiagnosticStatus::WARN;
    status.name = node_.get_fully_qualified_name();
    status.message = r2d::code_message(code);

    diagnostic_msgs::msg::KeyValue code_entry;
    code_entry.key = "code";
    code_entry.value = r2d::code_name(code);

    diagnostic_msgs::msg::KeyValue pipeline_entry;
    pipeline_entry.key = "pipeline";
    pipeline_entry.value = who ? who : "";

    status.values = {code_entry, pipeline_entry};
    array.status.push_back(status);
  });

  if (!array.status.empty()) {
    array.header.stamp = node_.now();
    pub_->publish(array);
  }
}

}  // namespace demo
