// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
#include "counter_node/interfaces.hpp"

#include <chrono>

namespace demo {

namespace {
[[maybe_unused]] double steady_now() { return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(); }
[[maybe_unused]] double system_now() { return std::chrono::duration<double>(std::chrono::system_clock::now().time_since_epoch()).count(); }
}  // namespace

// Everything is created here, before any callback can run (SPEC-03 §4.2). Each callback group is picked up with the node
// (`automatically_add_to_executor_with_node` defaults to true).
CounterNodeInterfaces::CounterNodeInterfaces(rclcpp::Node & node, CounterNodeEngine & engine) : node_(node), engine_(engine) {
  group_state_domain_1_ = node_.create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
  pub_count_pub_ = node_.create_publisher<std_msgs::msg::Int64>(names::kPubTopicCountPub, rclcpp::QoS(names::kPubQosDepthCountPub).reliable().durability_volatile());
  srv_reset_srv_ = node_.create_service<std_srvs::srv::Trigger>(names::kServiceNameResetSrv, [this](const std::shared_ptr<std_srvs::srv::Trigger::Request> req, std::shared_ptr<std_srvs::srv::Trigger::Response> res) { run_reset(*req, *res); }, rclcpp::ServicesQoS(), group_state_domain_1_);
  timer_tick_ = rclcpp::create_timer(&node_, node_.get_clock(), rclcpp::Duration(std::chrono::milliseconds(names::kPeriodMsTick)), [this]() { run_tick(); }, group_state_domain_1_);
}

void CounterNodeInterfaces::start() {
}

void CounterNodeInterfaces::run_reset(const std_srvs::srv::Trigger::Request & in, std_srvs::srv::Trigger::Response & res) {
  const auto run = engine_.enter();
  if (!run) { res = std_srvs::srv::Trigger::Response(); return; }
  const auto result = engine_.run_reset(run, in);
  if (!result) { res = std_srvs::srv::Trigger::Response(); return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
  res = std_srvs::srv::Trigger::Response();
  res.message = r.out__res__message;
  res.success = r.out__res__success;
}

void CounterNodeInterfaces::run_tick() {
  if (busy_tick_.exchange(true)) { engine_.report(r2d::Code::ERR_RUN_102, names::kPipelineTick); return; }
  struct BusyGuard { std::atomic<bool> & b; ~BusyGuard() { b.store(false); } } busy_guard{busy_tick_};
  const auto run = engine_.enter();
  if (!run) { return; }
  const auto result = engine_.run_tick(run);
  if (!result) { return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
  {
    std_msgs::msg::Int64 out{};  // value-initialised
    out.data = static_cast<std::int64_t>(r.out__count_pub__data);
    pub_count_pub_->publish(out);
  }
}

}  // namespace demo
