// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
#include <cstdio>
#include <cstdlib>
#include <exception>

#include "counter_node/app.hpp"

// A failure while starting or running (for example an invalid parameter value) ends the process
// with a message and a failure status, not with an abort.
int main(int argc, char ** argv) {
  try {
    return demo::CounterNodeApp(argc, argv).run();
  } catch (const std::exception & error) {
    std::fprintf(stderr, "%s: %s\n", demo::names::kNodeName, error.what());
  } catch (...) {
    std::fprintf(stderr, "%s: unknown error\n", demo::names::kNodeName);
  }
  return EXIT_FAILURE;
}
