// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 74d678a0f620298d24714a0ad2502171823ee9880c1a05a398425dec8b452f56
#include <memory>
#include <rclcpp/rclcpp.hpp>
#include "counter_node/counter_node_node.hpp"

int main(int argc, char ** argv) {
  rclcpp::init(argc, argv);
  auto node = std::make_shared<demo::CounterNode>();
  rclcpp::executors::SingleThreadedExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
