// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
#include <memory>
#include <rclcpp/rclcpp.hpp>
#include "counter_node/counter_node_node.hpp"

int main(int argc, char ** argv) {
  rclcpp::init(argc, argv);
  auto node = std::make_shared<demo::CounterNode>();
  rclcpp::executors::SingleThreadedExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
