// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
#include "counter_node/parameters.hpp"

#include <limits>
#include <string>
#include <utility>

namespace demo {

CounterNodeParameters::CounterNodeParameters(rclcpp::Node & node, CounterNodeEngine & engine)
    : engine_(engine) {
  // The effective values include launch-file and command-line overrides.
  Params initial;

  rcl_interfaces::msg::ParameterDescriptor d_limit;
  initial.limit = node.declare_parameter<std::int64_t>(
      names::kParamLimit, static_cast<std::int64_t>(std::int64_t{10}), d_limit);

  rcl_interfaces::msg::ParameterDescriptor d_step;
  d_step.integer_range.resize(1);
  d_step.integer_range[0].from_value = 1;
  d_step.integer_range[0].to_value = std::numeric_limits<std::int64_t>::max();
  d_step.integer_range[0].step = 0;
  initial.step = node.declare_parameter<std::int64_t>(
      names::kParamStep, static_cast<std::int64_t>(std::int64_t{1}), d_step);

  if (auto why = engine_.start(initial)) {
    throw rclcpp::exceptions::InvalidParameterValueException(*why);  // refuse to start
  }

  handle_ = binding::add_parameter_callback(
      node, [this](const std::vector<rclcpp::Parameter> & updates) { return on_set(updates); });
}

// Runs on the parameter-service thread, concurrently with the pipelines. It never touches state
// and never blocks a pipeline: the engine builds a whole new snapshot and swaps it in
// (SPEC-07 section 3.1, SPEC-12 section 5).
rcl_interfaces::msg::SetParametersResult CounterNodeParameters::on_set(
    const std::vector<rclcpp::Parameter> & updates) {
  auto reject = [this](std::string why) {
    engine_.report(r2d::Code::ERR_RUN_103, names::kParametersWho);
    rcl_interfaces::msg::SetParametersResult result;
    result.successful = false;
    result.reason = std::move(why);
    return result;
  };

  Params next = engine_.parameters();
  for (const auto & p : updates) {
    [[maybe_unused]] const std::string & name = p.get_name();
    if (name == names::kParamLimit) {
      next.limit = p.as_int();
    } else if (name == names::kParamStep) {
      next.step = p.as_int();
    }
  }

  // The whole batch is rejected, or nothing is published.
  if (auto why = engine_.update(next)) {
    return reject(*why);
  }

  rcl_interfaces::msg::SetParametersResult accepted;
  accepted.successful = true;
  return accepted;
}

}  // namespace demo
