// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
#include "gain_node/gain_node_node.hpp"

namespace processing {

GainNode::GainNode(const rclcpp::NodeOptions & options)
: Node(names::kNodeName, names::kNodeNamespace, options),
  parameters_(*this, engine_),
  interfaces_(*this, engine_),
  diagnostics_(*this, engine_) {
  engine_.open();  // a non-lifecycle node is active once constructed (SPEC-12 §6)
  interfaces_.start();  // startup pipelines run once, after the node is operational (SPEC-02 §7)
}

}  // namespace processing
