// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: afacacc8eaebf12ad2fa381378c7722cef92006d3f8f1a6872c97ac2f50d60ef
#include "gain_node/gain_node_node.hpp"

#include <chrono>
#include <limits>

namespace processing {

namespace {
[[maybe_unused]] double steady_now() { return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(); }
[[maybe_unused]] double system_now() { return std::chrono::duration<double>(std::chrono::system_clock::now().time_since_epoch()).count(); }
}  // namespace

GainNode::GainNode(const rclcpp::NodeOptions & options)
: Node("gain_node", "/processing", options), params_(Params{}) {
  declare_parameters();
  create_interfaces();
  gate_.open();  // a non-lifecycle node is active once constructed (SPEC-12 §6)
}

// Declared once, from the constructor. Both the initial values and every update go through validate().
void GainNode::declare_parameters() {
  Params initial;  // effective values include launch-file and command-line overrides
  rcl_interfaces::msg::ParameterDescriptor d_max_gain;
  d_max_gain.description = "Largest gain a set_gain request may apply.";
  d_max_gain.floating_point_range.resize(1);
  d_max_gain.floating_point_range[0].from_value = 0.0;
  d_max_gain.floating_point_range[0].to_value = std::numeric_limits<double>::max();
  d_max_gain.floating_point_range[0].step = 0.0;
  initial.max_gain = declare_parameter<double>("max_gain", static_cast<double>(10.0), d_max_gain);
  if (auto why = validate(initial)) {
    throw rclcpp::exceptions::InvalidParameterValueException(*why);  // refuse to start
  }
  params_.publish([&](Params & slot) { slot = initial; });
  param_handle_ = add_on_set_parameters_callback(
    [this](const std::vector<rclcpp::Parameter> & updates) { return on_set_parameters(updates); });
}

// Runs on the parameter-service thread, concurrently with the pipelines. It never touches state and never blocks a pipeline:
// it builds a whole new snapshot and swaps it in (SPEC-07 §3.1, SPEC-12 §5).
rcl_interfaces::msg::SetParametersResult GainNode::on_set_parameters(const std::vector<rclcpp::Parameter> & updates) {
  auto reject = [this](std::string why) {
    diag_.report(r2d::Code::ERR_RUN_103, "parameters");
    rcl_interfaces::msg::SetParametersResult r;
    r.successful = false;
    r.reason = std::move(why);
    return r;
  };
  Params next = *params_.acquire();
  for (const auto & p : updates) {
    [[maybe_unused]] const std::string & name = p.get_name();
    if (name == "max_gain") {
      next.max_gain = p.as_double();
    }
  }
  if (auto why = validate(next)) return reject(*why);  // the whole batch is rejected, nothing is published
  if (!params_.publish([&](Params & slot) { slot = next; })) return reject("parameter store busy, retry");
  rcl_interfaces::msg::SetParametersResult ok;
  ok.successful = true;
  return ok;
}

// Everything is created here, before any callback can run (SPEC-03 §4.2). Each callback group is picked up with the node
// (`automatically_add_to_executor_with_node` defaults to true).
void GainNode::create_interfaces() {
  group_state_domain_1_ = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
  group_diagnostics_ = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
  pub_output_pub_ = create_publisher<std_msgs::msg::Float64>("/processing/output", rclcpp::QoS(10).reliable().durability_volatile());
  {
    rclcpp::SubscriptionOptions opts;
    opts.callback_group = group_state_domain_1_;
    sub_input_sub_apply_gain_ = create_subscription<std_msgs::msg::Float64>("/processing/input", rclcpp::QoS(10).reliable().durability_volatile(),
      [this](std_msgs::msg::Float64::ConstSharedPtr m) { run_apply_gain(*m); }, opts);
  }
  srv_get_gain_srv_ = create_service<my_interfaces::srv::GetGain>("/processing/get_gain", [this](const std::shared_ptr<my_interfaces::srv::GetGain::Request> req, std::shared_ptr<my_interfaces::srv::GetGain::Response> res) { run_handle_get(*req, *res); }, rclcpp::ServicesQoS(), group_state_domain_1_);
  srv_reset_gain_srv_ = create_service<std_srvs::srv::Trigger>("/processing/reset_gain", [this](const std::shared_ptr<std_srvs::srv::Trigger::Request> req, std::shared_ptr<std_srvs::srv::Trigger::Response> res) { run_handle_reset(*req, *res); }, rclcpp::ServicesQoS(), group_state_domain_1_);
  srv_set_gain_srv_ = create_service<my_interfaces::srv::SetGain>("/processing/set_gain", [this](const std::shared_ptr<my_interfaces::srv::SetGain::Request> req, std::shared_ptr<my_interfaces::srv::SetGain::Response> res) { run_handle_set(*req, *res); }, rclcpp::ServicesQoS(), group_state_domain_1_);
  diag_pub_ = create_publisher<diagnostic_msgs::msg::DiagnosticArray>("/diagnostics", rclcpp::QoS(10));
  diag_timer_ = rclcpp::create_timer(this, clock_diag_, rclcpp::Duration(std::chrono::seconds(1)), [this]() { drain_diagnostics(); }, group_diagnostics_);
}

void GainNode::drain_diagnostics() {
  diagnostic_msgs::msg::DiagnosticArray array;
  diag_.drain([&](r2d::Code code, const char * who) {
    diagnostic_msgs::msg::DiagnosticStatus status;
    status.level = code == r2d::Code::ERR_RUN_101 ? diagnostic_msgs::msg::DiagnosticStatus::ERROR : diagnostic_msgs::msg::DiagnosticStatus::WARN;
    status.name = get_fully_qualified_name();
    status.message = r2d::code_message(code);
    diagnostic_msgs::msg::KeyValue c, p;
    c.key = "code"; c.value = r2d::code_name(code);
    p.key = "pipeline"; p.value = who ? who : "";
    status.values = {c, p};
    array.status.push_back(status);
  });
  if (!array.status.empty()) {
    array.header.stamp = now();
    diag_pub_->publish(array);
  }
}

void GainNode::run_apply_gain(const std_msgs::msg::Float64 & in) {
  r2d::RunGate::Scope run(gate_);
  if (!run) { return; }
  const auto params = params_.acquire();  // one snapshot for the whole execution (SPEC-12 §5)
  ApplyGainResult r;
  if (!eval_apply_gain(in, *params, state_, 0.0, 0.0, r)) {
    diag_.report(r2d::Code::ERR_RUN_101, "apply_gain");  // preallocated ring: no allocation, no logging here
    return;
  }
  {
    std_msgs::msg::Float64 out{};  // value-initialised
    out.data = r.out__output_pub__data;
    pub_output_pub_->publish(out);
  }
}

void GainNode::run_handle_get(const my_interfaces::srv::GetGain::Request & in, my_interfaces::srv::GetGain::Response & res) {
  r2d::RunGate::Scope run(gate_);
  if (!run) { res = my_interfaces::srv::GetGain::Response(); return; }
  const auto params = params_.acquire();  // one snapshot for the whole execution (SPEC-12 §5)
  HandleGetResult r;
  if (!eval_handle_get(in, *params, state_, 0.0, 0.0, r)) {
    diag_.report(r2d::Code::ERR_RUN_101, "handle_get");  // preallocated ring: no allocation, no logging here
    res = my_interfaces::srv::GetGain::Response();  // a fault returns the default response (SPEC-02 §7 step 6)
    return;
  }
  res = my_interfaces::srv::GetGain::Response();
  res.gain = r.out__res__gain;
}

void GainNode::run_handle_reset(const std_srvs::srv::Trigger::Request & in, std_srvs::srv::Trigger::Response & res) {
  r2d::RunGate::Scope run(gate_);
  if (!run) { res = std_srvs::srv::Trigger::Response(); return; }
  const auto params = params_.acquire();  // one snapshot for the whole execution (SPEC-12 §5)
  HandleResetResult r;
  if (!eval_handle_reset(in, *params, state_, 0.0, 0.0, r)) {
    diag_.report(r2d::Code::ERR_RUN_101, "handle_reset");  // preallocated ring: no allocation, no logging here
    res = std_srvs::srv::Trigger::Response();  // a fault returns the default response (SPEC-02 §7 step 6)
    return;
  }
  state_.gain = r.next_gain;  // step 5: commit
  res = std_srvs::srv::Trigger::Response();
  res.message = r.out__res__message;
  res.success = r.out__res__success;
}

void GainNode::run_handle_set(const my_interfaces::srv::SetGain::Request & in, my_interfaces::srv::SetGain::Response & res) {
  r2d::RunGate::Scope run(gate_);
  if (!run) { res = my_interfaces::srv::SetGain::Response(); return; }
  const auto params = params_.acquire();  // one snapshot for the whole execution (SPEC-12 §5)
  HandleSetResult r;
  if (!eval_handle_set(in, *params, state_, 0.0, 0.0, r)) {
    diag_.report(r2d::Code::ERR_RUN_101, "handle_set");  // preallocated ring: no allocation, no logging here
    res = my_interfaces::srv::SetGain::Response();  // a fault returns the default response (SPEC-02 §7 step 6)
    return;
  }
  state_.gain = r.next_gain;  // step 5: commit
  res = my_interfaces::srv::SetGain::Response();
  res.accepted = r.out__res__accepted;
  res.applied = r.out__res__applied;
}

}  // namespace processing
