// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
#include "gain_node/interfaces.hpp"

#include <chrono>

namespace processing {

namespace {
[[maybe_unused]] double steady_now() { return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(); }
[[maybe_unused]] double system_now() { return std::chrono::duration<double>(std::chrono::system_clock::now().time_since_epoch()).count(); }
}  // namespace

// Everything is created here, before any callback can run (SPEC-03 §4.2). Each callback group is picked up with the node
// (`automatically_add_to_executor_with_node` defaults to true).
GainNodeInterfaces::GainNodeInterfaces(rclcpp::Node & node, GainNodeEngine & engine) : node_(node), engine_(engine) {
  group_state_domain_1_ = node_.create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
  pub_output_pub_ = node_.create_publisher<std_msgs::msg::Float64>(names::kPubTopicOutputPub, rclcpp::QoS(names::kPubQosDepthOutputPub).reliable().durability_volatile());
  {
    rclcpp::SubscriptionOptions opts;
    opts.callback_group = group_state_domain_1_;
    sub_input_sub_apply_gain_ = node_.create_subscription<std_msgs::msg::Float64>(names::kSubTopicInputSub, rclcpp::QoS(names::kSubQosDepthInputSub).reliable().durability_volatile(),
      [this](std_msgs::msg::Float64::ConstSharedPtr m) { run_apply_gain(*m); }, opts);
  }
  srv_get_gain_srv_ = node_.create_service<my_interfaces::srv::GetGain>(names::kServiceNameGetGainSrv, [this](const std::shared_ptr<my_interfaces::srv::GetGain::Request> req, std::shared_ptr<my_interfaces::srv::GetGain::Response> res) { run_handle_get(*req, *res); }, rclcpp::ServicesQoS(), group_state_domain_1_);
  srv_reset_gain_srv_ = node_.create_service<std_srvs::srv::Trigger>(names::kServiceNameResetGainSrv, [this](const std::shared_ptr<std_srvs::srv::Trigger::Request> req, std::shared_ptr<std_srvs::srv::Trigger::Response> res) { run_handle_reset(*req, *res); }, rclcpp::ServicesQoS(), group_state_domain_1_);
  srv_set_gain_srv_ = node_.create_service<my_interfaces::srv::SetGain>(names::kServiceNameSetGainSrv, [this](const std::shared_ptr<my_interfaces::srv::SetGain::Request> req, std::shared_ptr<my_interfaces::srv::SetGain::Response> res) { run_handle_set(*req, *res); }, rclcpp::ServicesQoS(), group_state_domain_1_);
}

void GainNodeInterfaces::start() {
}

void GainNodeInterfaces::run_apply_gain(const std_msgs::msg::Float64 & in) {
  const auto run = engine_.enter();
  if (!run) { return; }
  const auto result = engine_.run_apply_gain(run, in);
  if (!result) { return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
  {
    std_msgs::msg::Float64 out{};  // value-initialised
    out.data = r.out__output_pub__data;
    pub_output_pub_->publish(out);
  }
}

void GainNodeInterfaces::run_handle_get(const my_interfaces::srv::GetGain::Request & in, my_interfaces::srv::GetGain::Response & res) {
  const auto run = engine_.enter();
  if (!run) { res = my_interfaces::srv::GetGain::Response(); return; }
  const auto result = engine_.run_handle_get(run, in);
  if (!result) { res = my_interfaces::srv::GetGain::Response(); return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
  res = my_interfaces::srv::GetGain::Response();
  res.gain = r.out__res__gain;
}

void GainNodeInterfaces::run_handle_reset(const std_srvs::srv::Trigger::Request & in, std_srvs::srv::Trigger::Response & res) {
  const auto run = engine_.enter();
  if (!run) { res = std_srvs::srv::Trigger::Response(); return; }
  const auto result = engine_.run_handle_reset(run, in);
  if (!result) { res = std_srvs::srv::Trigger::Response(); return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
  res = std_srvs::srv::Trigger::Response();
  res.message = r.out__res__message;
  res.success = r.out__res__success;
}

void GainNodeInterfaces::run_handle_set(const my_interfaces::srv::SetGain::Request & in, my_interfaces::srv::SetGain::Response & res) {
  const auto run = engine_.enter();
  if (!run) { res = my_interfaces::srv::SetGain::Response(); return; }
  const auto result = engine_.run_handle_set(run, in);
  if (!result) { res = my_interfaces::srv::SetGain::Response(); return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
  res = my_interfaces::srv::SetGain::Response();
  res.accepted = r.out__res__accepted;
  res.applied = r.out__res__applied;
}

}  // namespace processing
