// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: afacacc8eaebf12ad2fa381378c7722cef92006d3f8f1a6872c97ac2f50d60ef
#include <memory>
#include <rclcpp/rclcpp.hpp>
#include "gain_node/gain_node_node.hpp"

int main(int argc, char ** argv) {
  rclcpp::init(argc, argv);
  auto node = std::make_shared<processing::GainNode>();
  rclcpp::executors::SingleThreadedExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
