// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
#include <cstdio>
#include <cstdlib>
#include <exception>

#include "gain_node/app.hpp"

// A failure while starting or running (for example an invalid parameter value) ends the process
// with a message and a failure status, not with an abort.
int main(int argc, char ** argv) {
  try {
    return processing::GainNodeApp(argc, argv).run();
  } catch (const std::exception & error) {
    std::fprintf(stderr, "%s: %s\n", processing::names::kNodeName, error.what());
  } catch (...) {
    std::fprintf(stderr, "%s: unknown error\n", processing::names::kNodeName);
  }
  return EXIT_FAILURE;
}
