// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
#include "gain_node/app.hpp"

int main(int argc, char ** argv) {
  return processing::GainNodeApp(argc, argv).run();
}
