// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
#include "gain_node/parameters.hpp"

#include <limits>
#include <string>
#include <utility>

namespace processing {

GainNodeParameters::GainNodeParameters(rclcpp::Node & node, GainNodeEngine & engine)
    : engine_(engine), logger_(node.get_logger()) {
  // The effective values include launch-file and command-line overrides.
  Params initial;

  rcl_interfaces::msg::ParameterDescriptor d_max_gain;
  d_max_gain.description = "Largest gain a set_gain request may apply.";
  d_max_gain.floating_point_range.resize(1);
  d_max_gain.floating_point_range[0].from_value = 0.0;
  d_max_gain.floating_point_range[0].to_value = std::numeric_limits<double>::max();
  d_max_gain.floating_point_range[0].step = 0.0;
  initial.max_gain = node.declare_parameter<double>(
      names::kParamMaxGain, static_cast<double>(10.0), d_max_gain);

  if (auto why = engine_.start(initial)) {
    throw rclcpp::exceptions::InvalidParameterValueException(*why);  // refuse to start
  }

  handle_ = binding::add_parameter_callback(
      node, [this](const std::vector<rclcpp::Parameter> & updates) { return on_set(updates); });
}

// Runs on the parameter-service thread, concurrently with the pipelines. It never touches state
// and never blocks a pipeline: the engine builds a whole new snapshot and swaps it in
// (SPEC-07 section 3.1, SPEC-12 section 5).
rcl_interfaces::msg::SetParametersResult GainNodeParameters::on_set(
    const std::vector<rclcpp::Parameter> & updates) {
  auto reject = [this](std::string why) {
    RCLCPP_WARN(logger_, "parameter update rejected: %s", why.c_str());
    engine_.report(r2d::Code::ERR_RUN_103, names::kParametersWho);
    rcl_interfaces::msg::SetParametersResult result;
    result.successful = false;
    result.reason = std::move(why);
    return result;
  };

  Params next = engine_.parameters();
  for (const auto & p : updates) {
    [[maybe_unused]] const std::string & name = p.get_name();
    if (name == names::kParamMaxGain) {
      next.max_gain = p.as_double();
    }
  }

  // The whole batch is rejected, or nothing is published.
  if (auto why = engine_.update(next)) {
    return reject(*why);
  }

  rcl_interfaces::msg::SetParametersResult accepted;
  accepted.successful = true;
  return accepted;
}

}  // namespace processing
