// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
#include "gain_node/parameters.hpp"

#include <limits>
#include <string>
#include <utility>

namespace processing {

GainNodeParameters::GainNodeParameters(rclcpp::Node & node, GainNodeEngine & engine) : engine_(engine) {
  Params initial;  // effective values include launch-file and command-line overrides
  rcl_interfaces::msg::ParameterDescriptor d_max_gain;
  d_max_gain.description = "Largest gain a set_gain request may apply.";
  d_max_gain.floating_point_range.resize(1);
  d_max_gain.floating_point_range[0].from_value = 0.0;
  d_max_gain.floating_point_range[0].to_value = std::numeric_limits<double>::max();
  d_max_gain.floating_point_range[0].step = 0.0;
  initial.max_gain = node.declare_parameter<double>(names::kParamMaxGain, static_cast<double>(10.0), d_max_gain);
  if (auto why = engine_.start(initial)) {
    throw rclcpp::exceptions::InvalidParameterValueException(*why);  // refuse to start
  }
  handle_ = node.add_on_set_parameters_callback(
    [this](const std::vector<rclcpp::Parameter> & updates) { return on_set(updates); });
}

// Runs on the parameter-service thread, concurrently with the pipelines. It never touches state and never blocks a pipeline:
// the engine builds a whole new snapshot and swaps it in (SPEC-07 §3.1, SPEC-12 §5).
rcl_interfaces::msg::SetParametersResult GainNodeParameters::on_set(const std::vector<rclcpp::Parameter> & updates) {
  auto reject = [this](std::string why) {
    engine_.report(r2d::Code::ERR_RUN_103, names::kParametersWho);
    rcl_interfaces::msg::SetParametersResult r;
    r.successful = false;
    r.reason = std::move(why);
    return r;
  };
  Params next = engine_.parameters();
  for (const auto & p : updates) {
    [[maybe_unused]] const std::string & name = p.get_name();
    if (name == names::kParamMaxGain) {
      next.max_gain = p.as_double();
    }
  }
  if (auto why = engine_.update(next)) return reject(*why);  // the whole batch is rejected, nothing is published
  rcl_interfaces::msg::SetParametersResult ok;
  ok.successful = true;
  return ok;
}

}  // namespace processing
