// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
// The application: owns the ROS context, the node and the executor, and runs them. `main()` only
// creates it and calls `run()`.
#pragma once

#include <memory>

#include <rclcpp/rclcpp.hpp>

#include "link_watchdog_node/link_watchdog_node_node.hpp"
#include "link_watchdog_node/ros_binding.hpp"

namespace monitoring {

class LinkWatchdogNodeApp {
 public:
  LinkWatchdogNodeApp(int argc, char ** argv);
  LinkWatchdogNodeApp(const LinkWatchdogNodeApp &) = delete;
  LinkWatchdogNodeApp & operator=(const LinkWatchdogNodeApp &) = delete;

  // Spins until the context is shut down (for example by Ctrl-C). Returns the exit status.
  int run();

 private:
  // Initialises ROS first and shuts it down last, after the node and the executor are gone.
  struct RosContext {
    RosContext(int argc, char ** argv) { binding::init(argc, argv); }
    ~RosContext() { binding::shutdown(); }
    RosContext(const RosContext &) = delete;
    RosContext & operator=(const RosContext &) = delete;
  };

  RosContext context_;
  std::shared_ptr<LinkWatchdogNode> node_;
  std::unique_ptr<rclcpp::Executor> executor_;
};

}  // namespace monitoring
