// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
// Publishes what the engine's diagnostics ring collected, on a timer of its own (SPEC-12 section 7).
#pragma once
#include <rclcpp/rclcpp.hpp>
#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include "link_watchdog_node/engine.hpp"
#include "link_watchdog_node/interface_names.hpp"

namespace monitoring {

class LinkWatchdogNodeDiagnostics {
public:
  LinkWatchdogNodeDiagnostics(rclcpp::Node & node, LinkWatchdogNodeEngine & engine);
  LinkWatchdogNodeDiagnostics(const LinkWatchdogNodeDiagnostics &) = delete;
  LinkWatchdogNodeDiagnostics & operator=(const LinkWatchdogNodeDiagnostics &) = delete;

private:
  void drain();

  rclcpp::Node & node_;
  LinkWatchdogNodeEngine & engine_;
  rclcpp::CallbackGroup::SharedPtr group_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr pub_;
  rclcpp::Clock::SharedPtr clock_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
  rclcpp::TimerBase::SharedPtr timer_;
};

}  // namespace monitoring
