// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
// The ROS-free core of the node. It owns the parameter snapshots, the state, the run gate and the
// diagnostics ring, and has one `run_<pipeline>` method per pipeline: evaluate, commit the state,
// return the outputs to publish. It never publishes: the adapters (interfaces.hpp,
// parameters.hpp, diagnostics.hpp) feed it and publish what it returns.
#pragma once

#include <optional>
#include <string>

#include "link_watchdog_node/interface_names.hpp"
#include "link_watchdog_node/pipelines.hpp"
#include "link_watchdog_node/runtime.hpp"

namespace monitoring {

class LinkWatchdogNodeEngine {
 public:
  LinkWatchdogNodeEngine() : params_(Params{}) {}
  LinkWatchdogNodeEngine(const LinkWatchdogNodeEngine &) = delete;
  LinkWatchdogNodeEngine & operator=(const LinkWatchdogNodeEngine &) = delete;

  // ---- parameters -----------------------------------------------------------------------------
  // Both validate. A rejected value is returned as the reason and nothing changes
  // (SPEC-07 section 3.1).

  std::optional<std::string> start(const Params & initial) {
    if (auto why = validate(initial)) {
      return why;
    }
    params_.publish([&](Params & slot) { slot = initial; });
    return std::nullopt;
  }

  Params parameters() { return *params_.acquire(); }

  std::optional<std::string> update(const Params & next) {
    if (auto why = validate(next)) {
      return why;
    }
    if (!params_.publish([&](Params & slot) { slot = next; })) {
      return std::string("parameter store busy, retry");
    }
    return std::nullopt;
  }

  // ---- run gate -------------------------------------------------------------------------------
  // Closed until `open()`. A pipeline runs only while its caller holds the `Scope` that `enter()`
  // returns, and the caller keeps it until it has published the result (SPEC-12 section 6).
  // Check it with `if (!run)`.

  void open() noexcept { gate_.open(); }

  r2d::RunGate::Scope enter() noexcept { return r2d::RunGate::Scope(gate_); }

  // ---- diagnostics ----------------------------------------------------------------------------
  // Any thread reports; one consumer drains (SPEC-12 section 7).

  void report(r2d::Code code, const char * who) noexcept { diag_.report(code, who); }

  template <class Emit>
  void drain_diagnostics(Emit && emit) {
    diag_.drain(emit);
  }

  // ---- pipelines ------------------------------------------------------------------------------
  // `In` is the trigger's message or request type. A pipeline returns nothing when a numeric
  // fault stopped it: the fault is reported as ERR_RUN_101 and nothing is committed.

  std::optional<BootResult> run_boot(const r2d::RunGate::Scope &, double now_sec) {
    // One snapshot for the whole execution (SPEC-12 section 5).
    const auto params = params_.acquire();

    BootResult r;
    if (!eval_boot(*params, state_, now_sec, 0.0, r)) {
      // A preallocated ring: no allocation and no logging here.
      diag_.report(r2d::Code::ERR_RUN_101, names::kPipelineBoot);
      return std::nullopt;
    }

    // Step 5: commit.
    state_.last_seen = r.next_last_seen;

    return r;
  }

  std::optional<CheckLinkResult> run_check_link(const r2d::RunGate::Scope &, double now_sec) {
    // One snapshot for the whole execution (SPEC-12 section 5).
    const auto params = params_.acquire();

    CheckLinkResult r;
    if (!eval_check_link(*params, state_, now_sec, 0.0, r)) {
      // A preallocated ring: no allocation and no logging here.
      diag_.report(r2d::Code::ERR_RUN_101, names::kPipelineCheckLink);
      return std::nullopt;
    }

    return r;
  }

  template <class In>
  std::optional<OnHeartbeatResult> run_on_heartbeat(
    const r2d::RunGate::Scope &, const In & in, double now_sec) {
    // One snapshot for the whole execution (SPEC-12 section 5).
    const auto params = params_.acquire();

    OnHeartbeatResult r;
    if (!eval_on_heartbeat(in, *params, state_, now_sec, 0.0, r)) {
      // A preallocated ring: no allocation and no logging here.
      diag_.report(r2d::Code::ERR_RUN_101, names::kPipelineOnHeartbeat);
      return std::nullopt;
    }

    // Step 5: commit.
    state_.last_seen = r.next_last_seen;

    return r;
  }

 private:
  // One slot per thread (1), the current one and a free one (SPEC-12 section 5).
  r2d::SnapshotRing<Params, 3> params_;

  // Touched only through the callback group of the pipelines that use it (SPEC-12 section 3).
  State state_;

  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
};

}  // namespace monitoring
