// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
// The ROS-free core of the node. It owns the parameter snapshots, the state, the run gate and the diagnostics ring, and has one
// `run_<pipeline>` method per pipeline: evaluate, commit the state, return the outputs to publish. It never publishes; the
// adapters (interfaces.hpp, parameters.hpp, diagnostics.hpp) feed it and publish what it returns. A caller must hold the
// `Scope` that `enter()` returns while it runs a pipeline and publishes the result (SPEC-12 section 6).
#pragma once
#include <optional>
#include <string>
#include "link_watchdog_node/interface_names.hpp"
#include "link_watchdog_node/pipelines.hpp"
#include "link_watchdog_node/runtime.hpp"

namespace monitoring {

class LinkWatchdogNodeEngine {
public:
  LinkWatchdogNodeEngine() : params_(Params{}) {}
  LinkWatchdogNodeEngine(const LinkWatchdogNodeEngine &) = delete;
  LinkWatchdogNodeEngine & operator=(const LinkWatchdogNodeEngine &) = delete;

  // Parameters. Both validate; a rejected value is returned as the reason and nothing changes (SPEC-07 section 3.1).
  std::optional<std::string> start(const Params & initial) {
    if (auto why = validate(initial)) return why;
    params_.publish([&](Params & slot) { slot = initial; });
    return std::nullopt;
  }
  Params parameters() { return *params_.acquire(); }
  std::optional<std::string> update(const Params & next) {
    if (auto why = validate(next)) return why;
    if (!params_.publish([&](Params & slot) { slot = next; })) return std::string("parameter store busy, retry");
    return std::nullopt;
  }

  // The run gate: closed until `open()`, and a pipeline only runs while its caller holds a `Scope` (check it with `if (!run)`).
  void open() noexcept { gate_.open(); }
  r2d::RunGate::Scope enter() noexcept { return r2d::RunGate::Scope(gate_); }

  // Diagnostics (SPEC-12 section 7): any thread reports, one consumer drains.
  void report(r2d::Code code, const char * who) noexcept { diag_.report(code, who); }
  template <class Emit>
  void drain_diagnostics(Emit && emit) { diag_.drain(emit); }

  // The pipelines. `In` is the trigger's message or request type. They return nothing when a numeric fault stopped the execution
  // (reported as ERR_RUN_101, nothing committed).
  std::optional<BootResult> run_boot(const r2d::RunGate::Scope &, double now_sec) {
    const auto params = params_.acquire();  // one snapshot for the whole execution (SPEC-12 §5)
    BootResult r;
    if (!eval_boot(*params, state_, now_sec, 0.0, r)) {
      diag_.report(r2d::Code::ERR_RUN_101, names::kPipelineBoot);  // preallocated ring: no allocation, no logging here
      return std::nullopt;
    }
    state_.last_seen = r.next_last_seen;  // step 5: commit
    return r;
  }

  std::optional<CheckLinkResult> run_check_link(const r2d::RunGate::Scope &, double now_sec) {
    const auto params = params_.acquire();  // one snapshot for the whole execution (SPEC-12 §5)
    CheckLinkResult r;
    if (!eval_check_link(*params, state_, now_sec, 0.0, r)) {
      diag_.report(r2d::Code::ERR_RUN_101, names::kPipelineCheckLink);  // preallocated ring: no allocation, no logging here
      return std::nullopt;
    }
    return r;
  }

  template <class In>
  std::optional<OnHeartbeatResult> run_on_heartbeat(const r2d::RunGate::Scope &, const In & in, double now_sec) {
    const auto params = params_.acquire();  // one snapshot for the whole execution (SPEC-12 §5)
    OnHeartbeatResult r;
    if (!eval_on_heartbeat(in, *params, state_, now_sec, 0.0, r)) {
      diag_.report(r2d::Code::ERR_RUN_101, names::kPipelineOnHeartbeat);  // preallocated ring: no allocation, no logging here
      return std::nullopt;
    }
    state_.last_seen = r.next_last_seen;  // step 5: commit
    return r;
  }

private:
  r2d::SnapshotRing<Params, 3> params_;  // 3 = threads (1) + 2 (SPEC-12 §5)
  State state_;                                      // touched only through the callback group of the pipelines that use it (SPEC-12 §3)
  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
};

}  // namespace monitoring
