// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
// The ROS side of the pipelines: creates the publishers, subscriptions, services and timers,
// hands what arrives to the engine and what the engine returns to the publishers.
#pragma once

#include <atomic>
#include <chrono>
#include <memory>

#include <rclcpp/rclcpp.hpp>

#include <std_msgs/msg/bool.hpp>
#include <std_msgs/msg/empty.hpp>
#include <std_msgs/msg/float64.hpp>

#include "link_watchdog_node/engine.hpp"
#include "link_watchdog_node/interface_names.hpp"
#include "link_watchdog_node/ros_binding.hpp"

namespace monitoring {

class LinkWatchdogNodeInterfaces {
 public:
  LinkWatchdogNodeInterfaces(rclcpp::Node & node, LinkWatchdogNodeEngine & engine);
  LinkWatchdogNodeInterfaces(const LinkWatchdogNodeInterfaces &) = delete;
  LinkWatchdogNodeInterfaces & operator=(const LinkWatchdogNodeInterfaces &) = delete;

  // Runs the startup pipelines once. The node calls it when it is operational
  // (SPEC-02 section 7).
  void start();

 private:
  void run_boot();
  void run_check_link();
  void run_on_heartbeat(const std_msgs::msg::Empty & in);

  rclcpp::Node & node_;
  LinkWatchdogNodeEngine & engine_;

  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr pub_age_pub_;
  rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr pub_alive_pub_;
  rclcpp::TimerBase::SharedPtr timer_check_link_;
  std::atomic<bool> busy_check_link_{false};
  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr sub_heartbeat_sub_on_heartbeat_;
  rclcpp::Clock::SharedPtr clock_steady_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
};

}  // namespace monitoring
