// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
// Every name and number the manifest gives the node: topics, services, QoS depths, timer periods,
// parameter names and pipeline names. The rest of the generated code refers to these constants
// and repeats no such literal.
#pragma once

#include <cstddef>
#include <cstdint>

namespace monitoring::names {

// The node
inline constexpr char kNodeName[] = "link_watchdog_node";
inline constexpr char kNodeNamespace[] = "/monitoring";
inline constexpr std::size_t kExecutorThreads = 1;

// Diagnostics
inline constexpr char kDiagnosticsTopic[] = "/diagnostics";
inline constexpr std::size_t kDiagnosticsQosDepth = 10;
inline constexpr std::int64_t kDiagnosticsPeriodS = 1;

// Publishers
inline constexpr char kPubTopicAgePub[] = "/monitoring/heartbeat_age";
inline constexpr std::size_t kPubQosDepthAgePub = 10;
inline constexpr char kPubTopicAlivePub[] = "/monitoring/link_alive";
inline constexpr std::size_t kPubQosDepthAlivePub = 10;

// Subscribers
inline constexpr char kSubTopicHeartbeatSub[] = "/monitoring/heartbeat";
inline constexpr std::size_t kSubQosDepthHeartbeatSub = 10;

// Pipelines
inline constexpr char kPipelineBoot[] = "boot";
inline constexpr char kPipelineCheckLink[] = "check_link";
inline constexpr std::int64_t kPeriodMsCheckLink = 200;
inline constexpr char kPipelineOnHeartbeat[] = "on_heartbeat";

// Parameters
inline constexpr char kParametersWho[] = "parameters";
inline constexpr char kParamTimeoutS[] = "timeout_s";

}  // namespace monitoring::names
