// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
// The ROS node. It only wires its parts together, in this construction order: the engine (the
// ROS-free core), the parameters, the interfaces (publishers, subscriptions, services, timers)
// and the diagnostics.
#pragma once

#include <rclcpp/rclcpp.hpp>

#include "link_watchdog_node/diagnostics.hpp"
#include "link_watchdog_node/engine.hpp"
#include "link_watchdog_node/interfaces.hpp"
#include "link_watchdog_node/parameters.hpp"

namespace monitoring {

class LinkWatchdogNode : public rclcpp::Node {
 public:
  explicit LinkWatchdogNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

 private:
  LinkWatchdogNodeEngine engine_;
  LinkWatchdogNodeParameters parameters_;
  LinkWatchdogNodeInterfaces interfaces_;
  LinkWatchdogNodeDiagnostics diagnostics_;
};

}  // namespace monitoring
