// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
#pragma once
#include <atomic>
#include <chrono>
#include <memory>
#include <string>
#include <vector>
#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/bool.hpp>
#include <std_msgs/msg/empty.hpp>
#include <std_msgs/msg/float64.hpp>
#include "link_watchdog_node/pipelines.hpp"
#include "link_watchdog_node/runtime.hpp"

namespace monitoring {

class LinkWatchdogNode : public rclcpp::Node {
public:
  explicit LinkWatchdogNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

private:
  void declare_parameters();       // constructor only: declaration, no pipeline resources
  rcl_interfaces::msg::SetParametersResult on_set_parameters(const std::vector<rclcpp::Parameter> & updates);
  void create_interfaces();
  void drain_diagnostics();
  void run_boot();
  void run_check_link();
  void run_on_heartbeat(const std_msgs::msg::Empty & in);

  r2d::SnapshotRing<Params, 3> params_;  // 3 = threads (1) + 2 (SPEC-12 §5)
  State state_;                                      // touched only through the callback group of the pipelines that use it (SPEC-12 §3)
  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
  OnSetParametersCallbackHandle::SharedPtr param_handle_;
  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::CallbackGroup::SharedPtr group_diagnostics_;
  rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr pub_age_pub_;
  rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr pub_alive_pub_;
  rclcpp::TimerBase::SharedPtr timer_check_link_;
  std::atomic<bool> busy_check_link_{false};
  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr sub_heartbeat_sub_on_heartbeat_;
  rclcpp::Clock::SharedPtr clock_steady_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr diag_pub_;
  rclcpp::TimerBase::SharedPtr diag_timer_;
  rclcpp::Clock::SharedPtr clock_diag_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
};

}  // namespace monitoring
