// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
// The ROS side of the parameters: declares them on the node (their values include launch-file and
// command-line overrides) and forwards every later update to the engine, which validates it
// (SPEC-07 section 3.1).
#pragma once

#include <vector>

#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>

#include "link_watchdog_node/engine.hpp"
#include "link_watchdog_node/interface_names.hpp"
#include "link_watchdog_node/ros_binding.hpp"

namespace monitoring {

class LinkWatchdogNodeParameters {
 public:
  // Throws rclcpp::exceptions::InvalidParameterValueException when a starting value is invalid:
  // the node then refuses to start.
  LinkWatchdogNodeParameters(rclcpp::Node & node, LinkWatchdogNodeEngine & engine);
  LinkWatchdogNodeParameters(const LinkWatchdogNodeParameters &) = delete;
  LinkWatchdogNodeParameters & operator=(const LinkWatchdogNodeParameters &) = delete;

 private:
  rcl_interfaces::msg::SetParametersResult on_set(const std::vector<rclcpp::Parameter> & updates);

  LinkWatchdogNodeEngine & engine_;
  binding::ParameterCallbackHandle handle_;
};

}  // namespace monitoring
