// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
// Parameters, state and the pipelines of the manifest as plain C++: no ROS dependency. Message
// types are template parameters.
#pragma once

#include <cmath>
#include <cstdint>
#include <optional>
#include <regex>
#include <string>
#include <vector>

#include "link_watchdog_node/runtime.hpp"

namespace monitoring {

struct Params {
  double timeout_s{2.0};
};

struct State {
  double last_seen{0.0};
};

// One validation function for the initial values and for every update, so both obey the same
// rules.
inline std::optional<std::string> validate([[maybe_unused]] const Params & p) {
  if (!(p.timeout_s >= 0.1)) {
    return std::string("'timeout_s' out of range [0.1, inf]");
  }

  return std::nullopt;
}

// Pipeline `boot` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and
// publishes.
struct BootResult {
  double next_last_seen{};
};

inline bool eval_boot(
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] const State & state,
    [[maybe_unused]] double now_sec,
    [[maybe_unused]] double dt_sec,
    BootResult & out) {
  bool fault = false;

  const double n0 = now_sec;

  r2d::check_finite(n0, fault);
  if (fault) {
    return false;
  }

  out.next_last_seen = n0;
  return true;
}

// Pipeline `check_link` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and
// publishes.
struct CheckLinkResult {
  double out__age_pub__data{};
  bool out__alive_pub__data{};
};

inline bool eval_check_link(
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] const State & state,
    [[maybe_unused]] double now_sec,
    [[maybe_unused]] double dt_sec,
    CheckLinkResult & out) {
  bool fault = false;

  const double v_age = (now_sec - state.last_seen);
  const bool v_alive = (v_age <= params.timeout_s);

  r2d::check_finite(v_age, fault);
  if (fault) {
    return false;
  }

  out.out__age_pub__data = v_age;
  out.out__alive_pub__data = v_alive;
  return true;
}

// Pipeline `on_heartbeat` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and
// publishes.
struct OnHeartbeatResult {
  double next_last_seen{};
};

template <class In>
inline bool eval_on_heartbeat(
    [[maybe_unused]] const In & in,
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] const State & state,
    [[maybe_unused]] double now_sec,
    [[maybe_unused]] double dt_sec,
    OnHeartbeatResult & out) {
  bool fault = false;

  const double n0 = now_sec;

  r2d::check_finite(n0, fault);
  if (fault) {
    return false;
  }

  out.next_last_seen = n0;
  return true;
}

}  // namespace monitoring
