// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
#include "link_watchdog_node/interfaces.hpp"

#include <chrono>

namespace monitoring {

namespace {
[[maybe_unused]] double steady_now() { return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(); }
[[maybe_unused]] double system_now() { return std::chrono::duration<double>(std::chrono::system_clock::now().time_since_epoch()).count(); }
}  // namespace

// Everything is created here, before any callback can run (SPEC-03 §4.2). Each callback group is picked up with the node
// (`automatically_add_to_executor_with_node` defaults to true).
LinkWatchdogNodeInterfaces::LinkWatchdogNodeInterfaces(rclcpp::Node & node, LinkWatchdogNodeEngine & engine) : node_(node), engine_(engine) {
  group_state_domain_1_ = node_.create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
  pub_age_pub_ = node_.create_publisher<std_msgs::msg::Float64>(names::kPubTopicAgePub, rclcpp::QoS(names::kPubQosDepthAgePub).reliable().durability_volatile());
  pub_alive_pub_ = node_.create_publisher<std_msgs::msg::Bool>(names::kPubTopicAlivePub, rclcpp::QoS(names::kPubQosDepthAlivePub).reliable().durability_volatile());
  timer_check_link_ = rclcpp::create_timer(&node_, clock_steady_, rclcpp::Duration(std::chrono::milliseconds(names::kPeriodMsCheckLink)), [this]() { run_check_link(); }, group_state_domain_1_);
  {
    rclcpp::SubscriptionOptions opts;
    opts.callback_group = group_state_domain_1_;
    sub_heartbeat_sub_on_heartbeat_ = node_.create_subscription<std_msgs::msg::Empty>(names::kSubTopicHeartbeatSub, rclcpp::QoS(names::kSubQosDepthHeartbeatSub).reliable().durability_volatile(),
      [this](std_msgs::msg::Empty::ConstSharedPtr m) { run_on_heartbeat(*m); }, opts);
  }
}

void LinkWatchdogNodeInterfaces::start() {
  run_boot();
}

void LinkWatchdogNodeInterfaces::run_boot() {
  const auto run = engine_.enter();
  if (!run) { return; }
  const double now_sec = steady_now();
  const auto result = engine_.run_boot(run, now_sec);
  if (!result) { return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
}

void LinkWatchdogNodeInterfaces::run_check_link() {
  if (busy_check_link_.exchange(true)) { engine_.report(r2d::Code::ERR_RUN_102, names::kPipelineCheckLink); return; }
  struct BusyGuard { std::atomic<bool> & b; ~BusyGuard() { b.store(false); } } busy_guard{busy_check_link_};
  const auto run = engine_.enter();
  if (!run) { return; }
  const double now_sec = steady_now();
  const auto result = engine_.run_check_link(run, now_sec);
  if (!result) { return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
  {
    std_msgs::msg::Float64 out{};  // value-initialised
    out.data = r.out__age_pub__data;
    pub_age_pub_->publish(out);
  }
  {
    std_msgs::msg::Bool out{};  // value-initialised
    out.data = r.out__alive_pub__data;
    pub_alive_pub_->publish(out);
  }
}

void LinkWatchdogNodeInterfaces::run_on_heartbeat(const std_msgs::msg::Empty & in) {
  const auto run = engine_.enter();
  if (!run) { return; }
  const double now_sec = steady_now();
  const auto result = engine_.run_on_heartbeat(run, in, now_sec);
  if (!result) { return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
}

}  // namespace monitoring
