// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
#include "link_watchdog_node/interfaces.hpp"

#include <chrono>

namespace monitoring {

namespace {

using Seconds = std::chrono::duration<double>;

double steady_now() {
  return Seconds(std::chrono::steady_clock::now().time_since_epoch()).count();
}

}  // namespace

// Everything is created here, before any callback can run (SPEC-03 §4.2). Each callback group is
// picked up with the node (`automatically_add_to_executor_with_node` defaults to true).
LinkWatchdogNodeInterfaces::LinkWatchdogNodeInterfaces(
    rclcpp::Node & node, LinkWatchdogNodeEngine & engine)
    : node_(node), engine_(engine) {
  group_state_domain_1_ = node_.create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);

  pub_age_pub_ = node_.create_publisher<std_msgs::msg::Float64>(
      names::kPubTopicAgePub,
      rclcpp::QoS(names::kPubQosDepthAgePub).reliable().durability_volatile());
  pub_alive_pub_ = node_.create_publisher<std_msgs::msg::Bool>(
      names::kPubTopicAlivePub,
      rclcpp::QoS(names::kPubQosDepthAlivePub).reliable().durability_volatile());

  timer_check_link_ = binding::create_timer(
      node_,
      clock_steady_,
      std::chrono::milliseconds(names::kPeriodMsCheckLink),
      [this]() { run_check_link(); },
      group_state_domain_1_);

  sub_heartbeat_sub_on_heartbeat_ = binding::create_subscription<std_msgs::msg::Empty>(
      node_,
      names::kSubTopicHeartbeatSub,
      rclcpp::QoS(names::kSubQosDepthHeartbeatSub).reliable().durability_volatile(),
      [this](std_msgs::msg::Empty::ConstSharedPtr msg) { run_on_heartbeat(*msg); },
      group_state_domain_1_);
}

void LinkWatchdogNodeInterfaces::start() {
  run_boot();
}

void LinkWatchdogNodeInterfaces::run_boot() {
  const auto run = engine_.enter();
  if (!run) {
    return;
  }

  const double now_sec = steady_now();
  const auto result = engine_.run_boot(run, now_sec);
  if (!result) {
    // A numeric fault: the engine reported it (SPEC-02 section 7, step 6).
    return;
  }

  [[maybe_unused]] const auto & r = *result;
}

void LinkWatchdogNodeInterfaces::run_check_link() {
  // A firing while the previous execution still runs is skipped (ERR_RUN_102).
  r2d::BusyGuard busy(busy_check_link_);
  if (!busy) {
    engine_.report(r2d::Code::ERR_RUN_102, names::kPipelineCheckLink);
    return;
  }

  const auto run = engine_.enter();
  if (!run) {
    return;
  }

  const double now_sec = steady_now();
  const auto result = engine_.run_check_link(run, now_sec);
  if (!result) {
    // A numeric fault: the engine reported it (SPEC-02 section 7, step 6).
    return;
  }

  [[maybe_unused]] const auto & r = *result;

  {
    std_msgs::msg::Float64 out{};  // value-initialised
    out.data = r.out__age_pub__data;
    pub_age_pub_->publish(out);
  }

  {
    std_msgs::msg::Bool out{};  // value-initialised
    out.data = r.out__alive_pub__data;
    pub_alive_pub_->publish(out);
  }
}

void LinkWatchdogNodeInterfaces::run_on_heartbeat(const std_msgs::msg::Empty & in) {
  const auto run = engine_.enter();
  if (!run) {
    return;
  }

  const double now_sec = steady_now();
  const auto result = engine_.run_on_heartbeat(run, in, now_sec);
  if (!result) {
    // A numeric fault: the engine reported it (SPEC-02 section 7, step 6).
    return;
  }

  [[maybe_unused]] const auto & r = *result;
}

}  // namespace monitoring
