// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
#include "link_watchdog_node/link_watchdog_node_node.hpp"

namespace monitoring {

LinkWatchdogNode::LinkWatchdogNode(const rclcpp::NodeOptions & options)
: Node(names::kNodeName, names::kNodeNamespace, options),
  parameters_(*this, engine_),
  interfaces_(*this, engine_),
  diagnostics_(*this, engine_) {
  engine_.open();  // a non-lifecycle node is active once constructed (SPEC-12 §6)
  interfaces_.start();  // startup pipelines run once, after the node is operational (SPEC-02 §7)
}

}  // namespace monitoring
