// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
#include <cstdio>
#include <cstdlib>
#include <exception>

#include "link_watchdog_node/app.hpp"

// A failure while starting or running (for example an invalid parameter value) ends the process
// with a message and a failure status, not with an abort.
int main(int argc, char ** argv) {
  try {
    return monitoring::LinkWatchdogNodeApp(argc, argv).run();
  } catch (const std::exception & error) {
    std::fprintf(stderr, "%s: %s\n", monitoring::names::kNodeName, error.what());
  } catch (...) {
    std::fprintf(stderr, "%s: unknown error\n", monitoring::names::kNodeName);
  }
  return EXIT_FAILURE;
}
