// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
#include <memory>
#include <rclcpp/rclcpp.hpp>
#include "link_watchdog_node/link_watchdog_node_node.hpp"

int main(int argc, char ** argv) {
  rclcpp::init(argc, argv);
  auto node = std::make_shared<monitoring::LinkWatchdogNode>();
  rclcpp::executors::SingleThreadedExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
