// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 329679b48f8f38495b930263937dba441cbf9d18d9e8b5118ff17bb20e2b51e3
#include <memory>
#include <rclcpp/rclcpp.hpp>
#include "link_watchdog_node/link_watchdog_node_node.hpp"

int main(int argc, char ** argv) {
  rclcpp::init(argc, argv);
  auto node = std::make_shared<monitoring::LinkWatchdogNode>();
  rclcpp::executors::SingleThreadedExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
