// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
#include "link_watchdog_node/parameters.hpp"

#include <limits>
#include <string>
#include <utility>

namespace monitoring {

LinkWatchdogNodeParameters::LinkWatchdogNodeParameters(rclcpp::Node & node, LinkWatchdogNodeEngine & engine) : engine_(engine) {
  Params initial;  // effective values include launch-file and command-line overrides
  rcl_interfaces::msg::ParameterDescriptor d_timeout_s;
  d_timeout_s.description = "Seconds without a heartbeat before the link is reported down.";
  d_timeout_s.floating_point_range.resize(1);
  d_timeout_s.floating_point_range[0].from_value = 0.1;
  d_timeout_s.floating_point_range[0].to_value = std::numeric_limits<double>::max();
  d_timeout_s.floating_point_range[0].step = 0.0;
  initial.timeout_s = node.declare_parameter<double>(names::kParamTimeoutS, static_cast<double>(2.0), d_timeout_s);
  if (auto why = engine_.start(initial)) {
    throw rclcpp::exceptions::InvalidParameterValueException(*why);  // refuse to start
  }
  handle_ = node.add_on_set_parameters_callback(
    [this](const std::vector<rclcpp::Parameter> & updates) { return on_set(updates); });
}

// Runs on the parameter-service thread, concurrently with the pipelines. It never touches state and never blocks a pipeline:
// the engine builds a whole new snapshot and swaps it in (SPEC-07 §3.1, SPEC-12 §5).
rcl_interfaces::msg::SetParametersResult LinkWatchdogNodeParameters::on_set(const std::vector<rclcpp::Parameter> & updates) {
  auto reject = [this](std::string why) {
    engine_.report(r2d::Code::ERR_RUN_103, names::kParametersWho);
    rcl_interfaces::msg::SetParametersResult r;
    r.successful = false;
    r.reason = std::move(why);
    return r;
  };
  Params next = engine_.parameters();
  for (const auto & p : updates) {
    [[maybe_unused]] const std::string & name = p.get_name();
    if (name == names::kParamTimeoutS) {
      next.timeout_s = p.as_double();
    }
  }
  if (auto why = engine_.update(next)) return reject(*why);  // the whole batch is rejected, nothing is published
  rcl_interfaces::msg::SetParametersResult ok;
  ok.successful = true;
  return ok;
}

}  // namespace monitoring
