// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// The application: owns the ROS context, the node and the executor, and runs them. `main()` only
// creates it and calls `run()`.
#pragma once

#include <memory>

#include <rclcpp/rclcpp.hpp>

#include "speed_planner_node/speed_planner_node_node.hpp"
#include "speed_planner_node/ros_binding.hpp"

namespace planning {

class SpeedPlannerNodeApp {
 public:
  SpeedPlannerNodeApp(int argc, char ** argv);
  SpeedPlannerNodeApp(const SpeedPlannerNodeApp &) = delete;
  SpeedPlannerNodeApp & operator=(const SpeedPlannerNodeApp &) = delete;

  // Spins until the context is shut down (for example by Ctrl-C). Returns the exit status.
  int run();

 private:
  // Initialises ROS first and shuts it down last, after the node and the executor are gone.
  struct RosContext {
    RosContext(int argc, char ** argv) { binding::init(argc, argv); }
    ~RosContext() { binding::shutdown(); }
    RosContext(const RosContext &) = delete;
    RosContext & operator=(const RosContext &) = delete;
  };

  RosContext context_;
  std::shared_ptr<SpeedPlannerNode> node_;
  std::unique_ptr<rclcpp::Executor> executor_;
};

}  // namespace planning
