// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// Publishes what the engine's diagnostics ring collected, on a timer of its own
// (SPEC-12 section 7).
#pragma once

#include <memory>

#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rclcpp/rclcpp.hpp>

#include "speed_planner_node/engine.hpp"
#include "speed_planner_node/interface_names.hpp"
#include "speed_planner_node/ros_binding.hpp"

namespace planning {

class SpeedPlannerNodeDiagnostics {
 public:
  SpeedPlannerNodeDiagnostics(rclcpp::Node & node, SpeedPlannerNodeEngine & engine);
  SpeedPlannerNodeDiagnostics(const SpeedPlannerNodeDiagnostics &) = delete;
  SpeedPlannerNodeDiagnostics & operator=(const SpeedPlannerNodeDiagnostics &) = delete;

 private:
  void drain();
  void log(r2d::Code code, const char * who, std::size_t count);

  rclcpp::Node & node_;
  SpeedPlannerNodeEngine & engine_;
  rclcpp::CallbackGroup::SharedPtr group_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr pub_;
  rclcpp::Clock::SharedPtr clock_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
  rclcpp::TimerBase::SharedPtr timer_;
};

}  // namespace planning
