// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// The ROS-free core of the node. It owns the parameter snapshots, the state, the run gate and the diagnostics ring, and has one
// `run_<pipeline>` method per pipeline: evaluate, commit the state, return the outputs to publish. It never publishes; the
// adapters (interfaces.hpp, parameters.hpp, diagnostics.hpp) feed it and publish what it returns. A caller must hold the
// `Scope` that `enter()` returns while it runs a pipeline and publishes the result (SPEC-12 section 6).
#pragma once
#include <optional>
#include <string>
#include "speed_planner_node/interface_names.hpp"
#include "speed_planner_node/pipelines.hpp"
#include "speed_planner_node/runtime.hpp"

namespace planning {

class SpeedPlannerNodeEngine {
public:
  SpeedPlannerNodeEngine() : params_(Params{}) {}
  SpeedPlannerNodeEngine(const SpeedPlannerNodeEngine &) = delete;
  SpeedPlannerNodeEngine & operator=(const SpeedPlannerNodeEngine &) = delete;

  // Parameters. Both validate; a rejected value is returned as the reason and nothing changes (SPEC-07 section 3.1).
  std::optional<std::string> start(const Params & initial) {
    if (auto why = validate(initial)) return why;
    params_.publish([&](Params & slot) { slot = initial; });
    return std::nullopt;
  }
  Params parameters() { return *params_.acquire(); }
  std::optional<std::string> update(const Params & next) {
    if (auto why = validate(next)) return why;
    if (!params_.publish([&](Params & slot) { slot = next; })) return std::string("parameter store busy, retry");
    return std::nullopt;
  }

  // The run gate: closed until `open()`, and a pipeline only runs while its caller holds a `Scope` (check it with `if (!run)`).
  void open() noexcept { gate_.open(); }
  r2d::RunGate::Scope enter() noexcept { return r2d::RunGate::Scope(gate_); }

  // Diagnostics (SPEC-12 section 7): any thread reports, one consumer drains.
  void report(r2d::Code code, const char * who) noexcept { diag_.report(code, who); }
  template <class Emit>
  void drain_diagnostics(Emit && emit) { diag_.drain(emit); }

  // The pipelines. `In` is the trigger's message or request type. They return nothing when a numeric fault stopped the execution
  // (reported as ERR_RUN_101, nothing committed).
  template <class In>
  std::optional<PlanResult> run_plan(const r2d::RunGate::Scope &, const In & in) {
    const auto params = params_.acquire();  // one snapshot for the whole execution (SPEC-12 §5)
    PlanResult r;
    if (!eval_plan(in, *params, state_, 0.0, 0.0, r)) {
      diag_.report(r2d::Code::ERR_RUN_101, names::kPipelinePlan);  // preallocated ring: no allocation, no logging here
      return std::nullopt;
    }
    state_.last_speed = r.next_last_speed;  // step 5: commit
    return r;
  }

private:
  r2d::SnapshotRing<Params, 3> params_;  // 3 = threads (1) + 2 (SPEC-12 §5)
  State state_;                                      // touched only through the callback group of the pipelines that use it (SPEC-12 §3)
  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
};

}  // namespace planning
