// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// Every name and number the manifest gives the node: topics, services, QoS depths, timer periods,
// parameter names and pipeline names. The rest of the generated code refers to these constants
// and repeats no such literal.
#pragma once

#include <cstddef>
#include <cstdint>

namespace planning::names {

// The node
inline constexpr char kNodeName[] = "speed_planner_node";
inline constexpr char kNodeNamespace[] = "/planning";
inline constexpr std::size_t kExecutorThreads = 1;

// Diagnostics
inline constexpr char kDiagnosticsTopic[] = "/diagnostics";
inline constexpr std::size_t kDiagnosticsQosDepth = 10;
inline constexpr std::int64_t kDiagnosticsPeriodS = 1;

// Publishers
inline constexpr char kPubTopicLabelPub[] = "/planning/label";
inline constexpr std::size_t kPubQosDepthLabelPub = 10;
inline constexpr char kPubTopicSpeedPub[] = "/planning/speed";
inline constexpr std::size_t kPubQosDepthSpeedPub = 10;

// Subscribers
inline constexpr char kSubTopicRangeSub[] = "/planning/range";
inline constexpr std::size_t kSubQosDepthRangeSub = 10;

// Pipelines
inline constexpr char kPipelinePlan[] = "plan";

// Parameters
inline constexpr char kParametersWho[] = "parameters";
inline constexpr char kParamSpeedLimit[] = "speed_limit";

}  // namespace planning::names
