// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// The ROS side of the pipelines: creates the publishers, subscriptions, services and timers,
// hands what arrives to the engine and what the engine returns to the publishers.
#pragma once

#include <atomic>
#include <chrono>
#include <memory>

#include <rclcpp/rclcpp.hpp>

#include <std_msgs/msg/float64.hpp>
#include <std_msgs/msg/string.hpp>

#include "speed_planner_node/engine.hpp"
#include "speed_planner_node/interface_names.hpp"
#include "speed_planner_node/ros_binding.hpp"

namespace planning {

class SpeedPlannerNodeInterfaces {
 public:
  SpeedPlannerNodeInterfaces(rclcpp::Node & node, SpeedPlannerNodeEngine & engine);
  SpeedPlannerNodeInterfaces(const SpeedPlannerNodeInterfaces &) = delete;
  SpeedPlannerNodeInterfaces & operator=(const SpeedPlannerNodeInterfaces &) = delete;

  // Runs the startup pipelines once. The node calls it when it is operational
  // (SPEC-02 section 7).
  void start();

 private:
  void run_plan(const std_msgs::msg::Float64 & in);

  rclcpp::Node & node_;
  SpeedPlannerNodeEngine & engine_;

  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr pub_label_pub_;
  rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr pub_speed_pub_;
  rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr sub_range_sub_plan_;
};

}  // namespace planning
