// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// What the manifest asks you to write, as plain functions in the global namespace `logic`. Put
// them in any .cpp file in your `logic/` folder and include this header
// (`#include "speed_planner_node/logic_api.hpp"`) so the compiler checks the signatures.
//
// Each function takes a final `bool & fault`: set it to true to abort the current execution (a
// numeric fault). Pipelines in different callback groups may call your functions at the same
// time, so they must be reentrant. `setup()` runs once when the node starts and `teardown()` once
// when it stops; both are optional.
#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace logic {

void setup();

void teardown();

/// A short label for a speed.
std::string describe(double speed, bool & fault);

/// Chooses a target speed from the distance ahead, the limit and the previous speed.
double plan_speed(double distance, double limit, double previous, bool & fault);

}  // namespace logic
