// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// The ROS side of the parameters: declares them on the node (their values include launch-file and
// command-line overrides) and forwards every later update to the engine, which validates it
// (SPEC-07 section 3.1).
#pragma once

#include <vector>

#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>

#include "speed_planner_node/engine.hpp"
#include "speed_planner_node/interface_names.hpp"
#include "speed_planner_node/ros_binding.hpp"

namespace planning {

class SpeedPlannerNodeParameters {
 public:
  // Throws rclcpp::exceptions::InvalidParameterValueException when a starting value is invalid:
  // the node then refuses to start.
  SpeedPlannerNodeParameters(rclcpp::Node & node, SpeedPlannerNodeEngine & engine);
  SpeedPlannerNodeParameters(const SpeedPlannerNodeParameters &) = delete;
  SpeedPlannerNodeParameters & operator=(const SpeedPlannerNodeParameters &) = delete;

 private:
  rcl_interfaces::msg::SetParametersResult on_set(const std::vector<rclcpp::Parameter> & updates);

  SpeedPlannerNodeEngine & engine_;
  rclcpp::Logger logger_;
  binding::ParameterCallbackHandle handle_;
};

}  // namespace planning
