// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// Parameters, state and the pipelines of the manifest as plain C++: no ROS dependency. Message types are template parameters.
#pragma once
#include <cmath>
#include <cstdint>
#include <optional>
#include <regex>
#include <string>
#include <vector>
#include "speed_planner_node/runtime.hpp"
#include "speed_planner_node/logic_api.hpp"

namespace planning {

struct Params {
  double speed_limit{2.0};
};

struct State {
  double last_speed{0.0};
};

// One validation function for the initial values and for every update, so both obey the same rules.
inline std::optional<std::string> validate([[maybe_unused]] const Params & p) {
  if (!(p.speed_limit >= 0.0)) return std::string("'speed_limit' out of range [0.0, inf]");
  return std::nullopt;
}

// Pipeline `plan` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and publishes.
struct PlanResult {
  double next_last_speed{};
  std::string out__label_pub__data{};
  double out__speed_pub__data{};
};

template <class In>
inline bool eval_plan([[maybe_unused]] const In & in, [[maybe_unused]] const Params & params, [[maybe_unused]] const State & state, [[maybe_unused]] double now_sec, [[maybe_unused]] double dt_sec, PlanResult & out) {
  bool fault = false;
  const double v_speed = ::logic::plan_speed(in.data, params.speed_limit, state.last_speed, fault);
  const std::string n4 = ::logic::describe(v_speed, fault);
  r2d::check_finite(v_speed, fault);
  if (fault) return false;
  out.next_last_speed = v_speed;
  out.out__label_pub__data = n4;
  out.out__speed_pub__data = v_speed;
  return true;
}

}  // namespace planning
