// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// The ROS node: it only wires its parts together. The parts, in construction order: the engine (the ROS-free core), the
// parameters, the interfaces (publishers, subscriptions, services, timers) and the diagnostics.
#pragma once
#include <rclcpp/rclcpp.hpp>
#include "speed_planner_node/diagnostics.hpp"
#include "speed_planner_node/engine.hpp"
#include "speed_planner_node/interfaces.hpp"
#include "speed_planner_node/parameters.hpp"

namespace planning {

class SpeedPlannerNode : public rclcpp::Node {
public:
  explicit SpeedPlannerNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~SpeedPlannerNode() override;  // runs the user's logic::teardown()

private:
  SpeedPlannerNodeEngine engine_;
  SpeedPlannerNodeParameters parameters_;
  SpeedPlannerNodeInterfaces interfaces_;
  SpeedPlannerNodeDiagnostics diagnostics_;
};

}  // namespace planning
