// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
#pragma once
#include <atomic>
#include <chrono>
#include <memory>
#include <string>
#include <vector>
#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/float64.hpp>
#include <std_msgs/msg/string.hpp>
#include "speed_planner_node/pipelines.hpp"
#include "speed_planner_node/runtime.hpp"

namespace planning {

class SpeedPlannerNode : public rclcpp::Node {
public:
  explicit SpeedPlannerNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~SpeedPlannerNode() override;  // runs the user's logic::teardown()

private:
  void declare_parameters();       // constructor only: declaration, no pipeline resources
  rcl_interfaces::msg::SetParametersResult on_set_parameters(const std::vector<rclcpp::Parameter> & updates);
  void create_interfaces();
  void drain_diagnostics();
  void run_plan(const std_msgs::msg::Float64 & in);

  r2d::SnapshotRing<Params, 3> params_;  // 3 = threads (1) + 2 (SPEC-12 §5)
  State state_;                                      // touched only through the callback group of the pipelines that use it (SPEC-12 §3)
  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
  OnSetParametersCallbackHandle::SharedPtr param_handle_;
  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::CallbackGroup::SharedPtr group_diagnostics_;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr pub_label_pub_;
  rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr pub_speed_pub_;
  rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr sub_range_sub_plan_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr diag_pub_;
  rclcpp::TimerBase::SharedPtr diag_timer_;
  rclcpp::Clock::SharedPtr clock_diag_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
};

}  // namespace planning
