// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
#include "imu_filter_node/diagnostics.hpp"

#include <chrono>

namespace sensors::chassis {

ImuFilterNodeDiagnostics::ImuFilterNodeDiagnostics(rclcpp::Node & node, ImuFilterNodeEngine & engine) : node_(node), engine_(engine) {
  group_ = node_.create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
  pub_ = node_.create_publisher<diagnostic_msgs::msg::DiagnosticArray>(names::kDiagnosticsTopic, rclcpp::QoS(names::kDiagnosticsQosDepth));
  timer_ = rclcpp::create_timer(&node_, clock_, rclcpp::Duration(std::chrono::seconds(names::kDiagnosticsPeriodS)), [this]() { drain(); }, group_);
}

void ImuFilterNodeDiagnostics::drain() {
  diagnostic_msgs::msg::DiagnosticArray array;
  engine_.drain_diagnostics([&](r2d::Code code, const char * who) {
    diagnostic_msgs::msg::DiagnosticStatus status;
    status.level = code == r2d::Code::ERR_RUN_101 ? diagnostic_msgs::msg::DiagnosticStatus::ERROR : diagnostic_msgs::msg::DiagnosticStatus::WARN;
    status.name = node_.get_fully_qualified_name();
    status.message = r2d::code_message(code);
    diagnostic_msgs::msg::KeyValue c, p;
    c.key = "code"; c.value = r2d::code_name(code);
    p.key = "pipeline"; p.value = who ? who : "";
    status.values = {c, p};
    array.status.push_back(status);
  });
  if (!array.status.empty()) {
    array.header.stamp = node_.now();
    pub_->publish(array);
  }
}

}  // namespace sensors::chassis
