// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
#include "imu_filter_node/imu_filter_node_node.hpp"

namespace sensors::chassis {

ImuFilterNode::ImuFilterNode(const rclcpp::NodeOptions & options)
    : Node(names::kNodeName, names::kNodeNamespace, options),
      parameters_(*this, engine_),
      interfaces_(*this, engine_),
      diagnostics_(*this, engine_) {
  // A non-lifecycle node is active once constructed (SPEC-12 section 6).
  engine_.open();

  // Startup pipelines run once, after the node is operational (SPEC-02 section 7).
  interfaces_.start();
}

}  // namespace sensors::chassis
