// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
#include "imu_filter_node/interfaces.hpp"

#include <chrono>

namespace sensors::chassis {

namespace {
[[maybe_unused]] double steady_now() { return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(); }
[[maybe_unused]] double system_now() { return std::chrono::duration<double>(std::chrono::system_clock::now().time_since_epoch()).count(); }
}  // namespace

// Everything is created here, before any callback can run (SPEC-03 §4.2). Each callback group is picked up with the node
// (`automatically_add_to_executor_with_node` defaults to true).
ImuFilterNodeInterfaces::ImuFilterNodeInterfaces(rclcpp::Node & node, ImuFilterNodeEngine & engine) : node_(node), engine_(engine) {
  group_state_domain_1_ = node_.create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
  pub_filtered_imu_pub_ = node_.create_publisher<sensor_msgs::msg::Imu>(names::kPubTopicFilteredImuPub, rclcpp::QoS(names::kPubQosDepthFilteredImuPub).reliable().durability_volatile());
  pub_status_pub_ = node_.create_publisher<std_msgs::msg::String>(names::kPubTopicStatusPub, rclcpp::QoS(names::kPubQosDepthStatusPub).reliable().durability_volatile());
  {
    rclcpp::SubscriptionOptions opts;
    opts.callback_group = group_state_domain_1_;
    sub_raw_imu_sub_filter_imu_ = node_.create_subscription<sensor_msgs::msg::Imu>(names::kSubTopicRawImuSub, rclcpp::QoS(names::kSubQosDepthRawImuSub).best_effort().durability_volatile(),
      [this](sensor_msgs::msg::Imu::ConstSharedPtr m) { run_filter_imu(*m); }, opts);
  }
}

void ImuFilterNodeInterfaces::start() {
}

void ImuFilterNodeInterfaces::run_filter_imu(const sensor_msgs::msg::Imu & in) {
  const auto run = engine_.enter();
  if (!run) { return; }
  const auto result = engine_.run_filter_imu(run, in);
  if (!result) { return; }  // a numeric fault was reported by the engine (SPEC-02 §7 step 6)
  [[maybe_unused]] const auto & r = *result;
  {
    sensor_msgs::msg::Imu out{};  // value-initialised
    out.header.frame_id = r.out__filtered_imu_pub__header__frame_id;
    out.linear_acceleration.z = r.out__filtered_imu_pub__linear_acceleration__z;
    pub_filtered_imu_pub_->publish(out);
  }
  {
    std_msgs::msg::String out{};  // value-initialised
    out.data = r.out__status_pub__data;
    pub_status_pub_->publish(out);
  }
}

}  // namespace sensors::chassis
