// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
#include "imu_filter_node/app.hpp"

int main(int argc, char ** argv) {
  return sensors::chassis::ImuFilterNodeApp(argc, argv).run();
}
