// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 094879502fffce53eb3f35eddc7baf56862ffaebd0a972b4b396f96971b8ccdd
#include <memory>
#include <rclcpp/rclcpp.hpp>
#include "imu_filter_node/imu_filter_node_node.hpp"

int main(int argc, char ** argv) {
  rclcpp::init(argc, argv);
  auto node = std::make_shared<sensors::chassis::ImuFilterNode>();
  rclcpp::executors::SingleThreadedExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
