// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
#include "imu_filter_node/parameters.hpp"

#include <limits>
#include <string>
#include <utility>

namespace sensors::chassis {

ImuFilterNodeParameters::ImuFilterNodeParameters(rclcpp::Node & node, ImuFilterNodeEngine & engine) : engine_(engine) {
  Params initial;  // effective values include launch-file and command-line overrides
  rcl_interfaces::msg::ParameterDescriptor d_alpha;
  d_alpha.description = "Low-pass smoothing factor.";
  d_alpha.floating_point_range.resize(1);
  d_alpha.floating_point_range[0].from_value = 0.0;
  d_alpha.floating_point_range[0].to_value = 1.0;
  d_alpha.floating_point_range[0].step = 0.0;
  initial.alpha = node.declare_parameter<double>(names::kParamAlpha, static_cast<double>(0.85), d_alpha);
  rcl_interfaces::msg::ParameterDescriptor d_max_accel;
  d_max_accel.floating_point_range.resize(1);
  d_max_accel.floating_point_range[0].from_value = 0.0;
  d_max_accel.floating_point_range[0].to_value = std::numeric_limits<double>::max();
  d_max_accel.floating_point_range[0].step = 0.0;
  initial.max_accel = node.declare_parameter<double>(names::kParamMaxAccel, static_cast<double>(20.0), d_max_accel);
  if (auto why = engine_.start(initial)) {
    throw rclcpp::exceptions::InvalidParameterValueException(*why);  // refuse to start
  }
  handle_ = node.add_on_set_parameters_callback(
    [this](const std::vector<rclcpp::Parameter> & updates) { return on_set(updates); });
}

// Runs on the parameter-service thread, concurrently with the pipelines. It never touches state and never blocks a pipeline:
// the engine builds a whole new snapshot and swaps it in (SPEC-07 §3.1, SPEC-12 §5).
rcl_interfaces::msg::SetParametersResult ImuFilterNodeParameters::on_set(const std::vector<rclcpp::Parameter> & updates) {
  auto reject = [this](std::string why) {
    engine_.report(r2d::Code::ERR_RUN_103, names::kParametersWho);
    rcl_interfaces::msg::SetParametersResult r;
    r.successful = false;
    r.reason = std::move(why);
    return r;
  };
  Params next = engine_.parameters();
  for (const auto & p : updates) {
    [[maybe_unused]] const std::string & name = p.get_name();
    if (name == names::kParamAlpha) {
      next.alpha = p.as_double();
    } else if (name == names::kParamMaxAccel) {
      next.max_accel = p.as_double();
    }
  }
  if (auto why = engine_.update(next)) return reject(*why);  // the whole batch is rejected, nothing is published
  rcl_interfaces::msg::SetParametersResult ok;
  ok.successful = true;
  return ok;
}

}  // namespace sensors::chassis
