// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
// The application: owns the ROS context, the node and the executor, and runs them. `main()` only
// creates it and calls `run()`.
#pragma once

#include <memory>

#include <rclcpp/rclcpp.hpp>

#include "gain_node/gain_node_node.hpp"
#include "gain_node/ros_binding.hpp"

namespace processing {

class GainNodeApp {
 public:
  GainNodeApp(int argc, char ** argv);
  GainNodeApp(const GainNodeApp &) = delete;
  GainNodeApp & operator=(const GainNodeApp &) = delete;

  // Spins until the context is shut down (for example by Ctrl-C). Returns the exit status.
  int run();

 private:
  // Initialises ROS first and shuts it down last, after the node and the executor are gone.
  struct RosContext {
    RosContext(int argc, char ** argv) { binding::init(argc, argv); }
    ~RosContext() { binding::shutdown(); }
    RosContext(const RosContext &) = delete;
    RosContext & operator=(const RosContext &) = delete;
  };

  RosContext context_;
  std::shared_ptr<GainNode> node_;
  std::unique_ptr<rclcpp::Executor> executor_;
};

}  // namespace processing
