// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
// Publishes what the engine's diagnostics ring collected, on a timer of its own
// (SPEC-12 section 7).
#pragma once

#include <memory>

#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rclcpp/rclcpp.hpp>

#include "gain_node/engine.hpp"
#include "gain_node/interface_names.hpp"
#include "gain_node/ros_binding.hpp"

namespace processing {

class GainNodeDiagnostics {
 public:
  GainNodeDiagnostics(rclcpp::Node & node, GainNodeEngine & engine);
  GainNodeDiagnostics(const GainNodeDiagnostics &) = delete;
  GainNodeDiagnostics & operator=(const GainNodeDiagnostics &) = delete;

 private:
  void drain();

  rclcpp::Node & node_;
  GainNodeEngine & engine_;
  rclcpp::CallbackGroup::SharedPtr group_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr pub_;
  rclcpp::Clock::SharedPtr clock_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
  rclcpp::TimerBase::SharedPtr timer_;
};

}  // namespace processing
