// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
#pragma once
#include <atomic>
#include <chrono>
#include <memory>
#include <string>
#include <vector>
#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>
#include <my_interfaces/srv/get_gain.hpp>
#include <my_interfaces/srv/set_gain.hpp>
#include <std_msgs/msg/float64.hpp>
#include <std_srvs/srv/trigger.hpp>
#include "gain_node/pipelines.hpp"
#include "gain_node/runtime.hpp"

namespace processing {

class GainNode : public rclcpp::Node {
public:
  explicit GainNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

private:
  void declare_parameters();       // constructor only: declaration, no pipeline resources
  rcl_interfaces::msg::SetParametersResult on_set_parameters(const std::vector<rclcpp::Parameter> & updates);
  void create_interfaces();
  void drain_diagnostics();
  void run_apply_gain(const std_msgs::msg::Float64 & in);
  void run_handle_get(const my_interfaces::srv::GetGain::Request & in, my_interfaces::srv::GetGain::Response & res);
  void run_handle_reset(const std_srvs::srv::Trigger::Request & in, std_srvs::srv::Trigger::Response & res);
  void run_handle_set(const my_interfaces::srv::SetGain::Request & in, my_interfaces::srv::SetGain::Response & res);

  r2d::SnapshotRing<Params, 3> params_;  // 3 = threads (1) + 2 (SPEC-12 §5)
  State state_;                                      // touched only through the callback group of the pipelines that use it (SPEC-12 §3)
  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
  OnSetParametersCallbackHandle::SharedPtr param_handle_;
  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::CallbackGroup::SharedPtr group_diagnostics_;
  rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr pub_output_pub_;
  rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr sub_input_sub_apply_gain_;
  rclcpp::Service<my_interfaces::srv::GetGain>::SharedPtr srv_get_gain_srv_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr srv_reset_gain_srv_;
  rclcpp::Service<my_interfaces::srv::SetGain>::SharedPtr srv_set_gain_srv_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr diag_pub_;
  rclcpp::TimerBase::SharedPtr diag_timer_;
  rclcpp::Clock::SharedPtr clock_diag_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
};

}  // namespace processing
