// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
// The ROS node. It only wires its parts together, in this construction order: the engine (the
// ROS-free core), the parameters, the interfaces (publishers, subscriptions, services, timers)
// and the diagnostics.
#pragma once

#include <rclcpp/rclcpp.hpp>

#include "gain_node/diagnostics.hpp"
#include "gain_node/engine.hpp"
#include "gain_node/interfaces.hpp"
#include "gain_node/parameters.hpp"

namespace processing {

class GainNode : public rclcpp::Node {
 public:
  explicit GainNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

 private:
  GainNodeEngine engine_;
  GainNodeParameters parameters_;
  GainNodeInterfaces interfaces_;
  GainNodeDiagnostics diagnostics_;
};

}  // namespace processing
