// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
// Every name and number the manifest gives the node: topics, services, QoS depths, timer periods, parameter names and
// pipeline names. The rest of the generated code refers to these constants and repeats no such literal.
#pragma once
#include <cstddef>
#include <cstdint>

namespace processing::names {

inline constexpr char kNodeName[] = "gain_node";
inline constexpr char kNodeNamespace[] = "/processing";
inline constexpr char kDiagnosticsTopic[] = "/diagnostics";
inline constexpr std::size_t kDiagnosticsQosDepth = 10;
inline constexpr std::int64_t kDiagnosticsPeriodS = 1;
inline constexpr char kParametersWho[] = "parameters";
inline constexpr std::size_t kExecutorThreads = 1;
inline constexpr char kPubTopicOutputPub[] = "/processing/output";
inline constexpr std::size_t kPubQosDepthOutputPub = 10;
inline constexpr char kSubTopicInputSub[] = "/processing/input";
inline constexpr std::size_t kSubQosDepthInputSub = 10;
inline constexpr char kServiceNameGetGainSrv[] = "/processing/get_gain";
inline constexpr char kServiceNameResetGainSrv[] = "/processing/reset_gain";
inline constexpr char kServiceNameSetGainSrv[] = "/processing/set_gain";
inline constexpr char kPipelineApplyGain[] = "apply_gain";
inline constexpr char kPipelineHandleGet[] = "handle_get";
inline constexpr char kPipelineHandleReset[] = "handle_reset";
inline constexpr char kPipelineHandleSet[] = "handle_set";
inline constexpr char kParamMaxGain[] = "max_gain";

}  // namespace processing::names
