// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
// The ROS side of the pipelines: creates the publishers, subscriptions, services and timers,
// hands what arrives to the engine and what the engine returns to the publishers.
#pragma once

#include <memory>

#include <rclcpp/rclcpp.hpp>

#include <my_interfaces/srv/get_gain.hpp>
#include <my_interfaces/srv/set_gain.hpp>
#include <std_msgs/msg/float64.hpp>
#include <std_srvs/srv/trigger.hpp>

#include "gain_node/engine.hpp"
#include "gain_node/interface_names.hpp"
#include "gain_node/ros_binding.hpp"

namespace processing {

class GainNodeInterfaces {
 public:
  GainNodeInterfaces(rclcpp::Node & node, GainNodeEngine & engine);
  GainNodeInterfaces(const GainNodeInterfaces &) = delete;
  GainNodeInterfaces & operator=(const GainNodeInterfaces &) = delete;

  // Runs the startup pipelines once. The node calls it when it is operational
  // (SPEC-02 section 7).
  void start();

 private:
  void run_apply_gain(const std_msgs::msg::Float64 & in);
  void run_handle_get(
      const my_interfaces::srv::GetGain::Request & in, my_interfaces::srv::GetGain::Response & res);
  void run_handle_reset(
      const std_srvs::srv::Trigger::Request & in, std_srvs::srv::Trigger::Response & res);
  void run_handle_set(
      const my_interfaces::srv::SetGain::Request & in, my_interfaces::srv::SetGain::Response & res);

  rclcpp::Node & node_;
  GainNodeEngine & engine_;

  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr pub_output_pub_;
  rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr sub_input_sub_apply_gain_;
  rclcpp::Service<my_interfaces::srv::GetGain>::SharedPtr srv_get_gain_srv_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr srv_reset_gain_srv_;
  rclcpp::Service<my_interfaces::srv::SetGain>::SharedPtr srv_set_gain_srv_;
};

}  // namespace processing
