// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
// The ROS side of the parameters: declares them on the node (their values include launch-file and
// command-line overrides) and forwards every later update to the engine, which validates it
// (SPEC-07 section 3.1).
#pragma once

#include <vector>

#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>

#include "gain_node/engine.hpp"
#include "gain_node/interface_names.hpp"
#include "gain_node/ros_binding.hpp"

namespace processing {

class GainNodeParameters {
 public:
  // Throws rclcpp::exceptions::InvalidParameterValueException when a starting value is invalid:
  // the node then refuses to start.
  GainNodeParameters(rclcpp::Node & node, GainNodeEngine & engine);
  GainNodeParameters(const GainNodeParameters &) = delete;
  GainNodeParameters & operator=(const GainNodeParameters &) = delete;

 private:
  rcl_interfaces::msg::SetParametersResult on_set(const std::vector<rclcpp::Parameter> & updates);

  GainNodeEngine & engine_;
  binding::ParameterCallbackHandle handle_;
};

}  // namespace processing
