// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
// Parameters, state and the pipelines of the manifest as plain C++: no ROS dependency. Message
// types are template parameters.
#pragma once

#include <cmath>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include "gain_node/runtime.hpp"

namespace processing {

struct Params {
  double max_gain{10.0};
};

struct State {
  double gain{1.0};
};

// One validation function for the initial values and for every update, so both obey the same
// rules.
inline std::optional<std::string> validate([[maybe_unused]] const Params & p) {
  if (!(p.max_gain >= 0.0)) {
    return std::string("'max_gain' out of range [0.0, inf]");
  }

  return std::nullopt;
}

// Pipeline `apply_gain` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and
// publishes.
struct ApplyGainResult {
  double out__output_pub__data{};
};

template <class In>
inline bool eval_apply_gain(
    [[maybe_unused]] const In & in,
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] const State & state,
    [[maybe_unused]] double now_sec,
    [[maybe_unused]] double dt_sec,
    ApplyGainResult & out) {
  bool fault = false;

  const double v_scaled = (in.data * state.gain);

  r2d::check_finite(v_scaled, fault);
  if (fault) {
    return false;
  }

  out.out__output_pub__data = v_scaled;
  return true;
}

// Pipeline `handle_get` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and
// publishes.
struct HandleGetResult {
  double out__res__gain{};
};

template <class In>
inline bool eval_handle_get(
    [[maybe_unused]] const In & in,
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] const State & state,
    [[maybe_unused]] double now_sec,
    [[maybe_unused]] double dt_sec,
    HandleGetResult & out) {
  bool fault = false;

  const double n0 = state.gain;

  r2d::check_finite(n0, fault);
  if (fault) {
    return false;
  }

  out.out__res__gain = n0;
  return true;
}

// Pipeline `handle_reset` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and
// publishes.
struct HandleResetResult {
  double next_gain{};
  std::string out__res__message{};
  bool out__res__success{};
};

template <class In>
inline bool eval_handle_reset(
    [[maybe_unused]] const In & in,
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] const State & state,
    [[maybe_unused]] double now_sec,
    [[maybe_unused]] double dt_sec,
    HandleResetResult & out) {
  bool fault = false;

  const double n0 = 1.0;
  const std::string n1 = std::string("gain reset");
  const bool n2 = true;

  r2d::check_finite(n0, fault);
  if (fault) {
    return false;
  }

  out.next_gain = n0;
  out.out__res__message = n1;
  out.out__res__success = n2;
  return true;
}

// Pipeline `handle_set` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and
// publishes.
struct HandleSetResult {
  double next_gain{};
  bool out__res__accepted{};
  double out__res__applied{};
};

template <class In>
inline bool eval_handle_set(
    [[maybe_unused]] const In & in,
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] const State & state,
    [[maybe_unused]] double now_sec,
    [[maybe_unused]] double dt_sec,
    HandleSetResult & out) {
  bool fault = false;

  const bool v_ok = ((in.gain >= 0.0) && (in.gain <= params.max_gain));
  const double v_next = (v_ok ? in.gain : state.gain);

  r2d::check_finite(v_next, fault);
  if (fault) {
    return false;
  }

  out.next_gain = v_next;
  out.out__res__accepted = v_ok;
  out.out__res__applied = v_next;
  return true;
}

}  // namespace processing
