# Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
# IR hash: 746d5e920b285d996bad9eb570c5db8d78e04cd58df8e88bd248b8cc9436dd16
# `ros2 launch link_watchdog_node link_watchdog_node.launch.py` starts the node with the parameter file in config/.
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    params = os.path.join(get_package_share_directory("link_watchdog_node"), "config", "link_watchdog_node.params.yaml")
    return LaunchDescription([
        Node(package="link_watchdog_node", executable="link_watchdog_node", output="screen", parameters=[params]),
    ])
