// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
// Weak placeholders for everything in logic_api.hpp: a definition in your `logic/` folder
// replaces it. A missing function (or one whose signature differs from the header) is not a
// build error: it reports itself once and faults, so the pipeline that calls it stops with
// ERR_RUN_101 instead of computing with an invented value.
#include <cstdio>

#include "speed_planner_node/logic_api.hpp"

namespace logic {

namespace {

void not_implemented(const char * name) {
  std::fprintf(
      stderr,
      "nodesmith: logic::%s is not implemented in logic/ "
      "(or its signature differs from logic_api.hpp)\n",
      name);
}

}  // namespace

__attribute__((weak)) void setup() {}

__attribute__((weak)) void teardown() {}

__attribute__((weak)) std::string describe(double, bool & fault) {
  [[maybe_unused]] static const bool reported = (not_implemented("describe"), true);
  fault = true;
  return {};
}

__attribute__((weak)) double plan_speed(double, double, double, bool & fault) {
  [[maybe_unused]] static const bool reported = (not_implemented("plan_speed"), true);
  fault = true;
  return {};
}

}  // namespace logic
