// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
#include "speed_planner_node/app.hpp"

int main(int argc, char ** argv) {
  return planning::SpeedPlannerNodeApp(argc, argv).run();
}
