// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
#include <cstdio>
#include <cstdlib>
#include <exception>

#include "speed_planner_node/app.hpp"

// A failure while starting or running (for example an invalid parameter value) ends the process
// with a message and a failure status, not with an abort.
int main(int argc, char ** argv) {
  try {
    return planning::SpeedPlannerNodeApp(argc, argv).run();
  } catch (const std::exception & error) {
    std::fprintf(stderr, "%s: %s\n", planning::names::kNodeName, error.what());
  } catch (...) {
    std::fprintf(stderr, "%s: unknown error\n", planning::names::kNodeName);
  }
  return EXIT_FAILURE;
}
