// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
#include "speed_planner_node/speed_planner_node_node.hpp"

namespace planning {

SpeedPlannerNode::SpeedPlannerNode(const rclcpp::NodeOptions & options)
    : Node(names::kNodeName, names::kNodeNamespace, options),
      parameters_(*this, engine_),
      interfaces_(*this, engine_),
      diagnostics_(*this, engine_) {
  // The user's start-up hook: after a valid start-up, before any pipeline can run.
  logic::setup();

  // A non-lifecycle node is active once constructed (SPEC-12 section 6).
  engine_.open();

  // Startup pipelines run once, after the node is operational (SPEC-02 section 7).
  interfaces_.start();
}

SpeedPlannerNode::~SpeedPlannerNode() {
  logic::teardown();  // the user's stop hook
}

}  // namespace planning
