// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
#include "speed_planner_node/speed_planner_node_node.hpp"

#include <chrono>
#include <limits>
#include <stdexcept>
#include <utility>

namespace planning {

namespace {
[[maybe_unused]] double steady_now() { return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(); }
[[maybe_unused]] double system_now() { return std::chrono::duration<double>(std::chrono::system_clock::now().time_since_epoch()).count(); }
}  // namespace

SpeedPlannerNode::SpeedPlannerNode(const rclcpp::NodeOptions & options)
: Node("speed_planner_node", "/planning", options), params_(Params{}) {
  declare_parameters();
  create_interfaces();
  logic::setup();  // the user's start-up hook: after a valid start-up, before any pipeline can run
  gate_.open();  // a non-lifecycle node is active once constructed (SPEC-12 §6)
}

SpeedPlannerNode::~SpeedPlannerNode() {
  logic::teardown();  // the user's stop hook
}

// Declared once, from the constructor. Both the initial values and every update go through validate().
void SpeedPlannerNode::declare_parameters() {
  Params initial;  // effective values include launch-file and command-line overrides
  rcl_interfaces::msg::ParameterDescriptor d_speed_limit;
  d_speed_limit.description = "Highest speed the planner may ask for.";
  d_speed_limit.floating_point_range.resize(1);
  d_speed_limit.floating_point_range[0].from_value = 0.0;
  d_speed_limit.floating_point_range[0].to_value = std::numeric_limits<double>::max();
  d_speed_limit.floating_point_range[0].step = 0.0;
  initial.speed_limit = declare_parameter<double>("speed_limit", static_cast<double>(2.0), d_speed_limit);
  if (auto why = validate(initial)) {
    throw rclcpp::exceptions::InvalidParameterValueException(*why);  // refuse to start
  }
  params_.publish([&](Params & slot) { slot = initial; });
  param_handle_ = add_on_set_parameters_callback(
    [this](const std::vector<rclcpp::Parameter> & updates) { return on_set_parameters(updates); });
}

// Runs on the parameter-service thread, concurrently with the pipelines. It never touches state and never blocks a pipeline:
// it builds a whole new snapshot and swaps it in (SPEC-07 §3.1, SPEC-12 §5).
rcl_interfaces::msg::SetParametersResult SpeedPlannerNode::on_set_parameters(const std::vector<rclcpp::Parameter> & updates) {
  auto reject = [this](std::string why) {
    diag_.report(r2d::Code::ERR_RUN_103, "parameters");
    rcl_interfaces::msg::SetParametersResult r;
    r.successful = false;
    r.reason = std::move(why);
    return r;
  };
  Params next = *params_.acquire();
  for (const auto & p : updates) {
    [[maybe_unused]] const std::string & name = p.get_name();
    if (name == "speed_limit") {
      next.speed_limit = p.as_double();
    }
  }
  if (auto why = validate(next)) return reject(*why);  // the whole batch is rejected, nothing is published
  if (!params_.publish([&](Params & slot) { slot = next; })) return reject("parameter store busy, retry");
  rcl_interfaces::msg::SetParametersResult ok;
  ok.successful = true;
  return ok;
}

// Everything is created here, before any callback can run (SPEC-03 §4.2). Each callback group is picked up with the node
// (`automatically_add_to_executor_with_node` defaults to true).
void SpeedPlannerNode::create_interfaces() {
  group_state_domain_1_ = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
  group_diagnostics_ = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
  pub_label_pub_ = create_publisher<std_msgs::msg::String>("/planning/label", rclcpp::QoS(10).reliable().durability_volatile());
  pub_speed_pub_ = create_publisher<std_msgs::msg::Float64>("/planning/speed", rclcpp::QoS(10).reliable().durability_volatile());
  {
    rclcpp::SubscriptionOptions opts;
    opts.callback_group = group_state_domain_1_;
    sub_range_sub_plan_ = create_subscription<std_msgs::msg::Float64>("/planning/range", rclcpp::QoS(10).reliable().durability_volatile(),
      [this](std_msgs::msg::Float64::ConstSharedPtr m) { run_plan(*m); }, opts);
  }
  diag_pub_ = create_publisher<diagnostic_msgs::msg::DiagnosticArray>("/diagnostics", rclcpp::QoS(10));
  diag_timer_ = rclcpp::create_timer(this, clock_diag_, rclcpp::Duration(std::chrono::seconds(1)), [this]() { drain_diagnostics(); }, group_diagnostics_);
}

void SpeedPlannerNode::drain_diagnostics() {
  diagnostic_msgs::msg::DiagnosticArray array;
  diag_.drain([&](r2d::Code code, const char * who) {
    diagnostic_msgs::msg::DiagnosticStatus status;
    status.level = code == r2d::Code::ERR_RUN_101 ? diagnostic_msgs::msg::DiagnosticStatus::ERROR : diagnostic_msgs::msg::DiagnosticStatus::WARN;
    status.name = get_fully_qualified_name();
    status.message = r2d::code_message(code);
    diagnostic_msgs::msg::KeyValue c, p;
    c.key = "code"; c.value = r2d::code_name(code);
    p.key = "pipeline"; p.value = who ? who : "";
    status.values = {c, p};
    array.status.push_back(status);
  });
  if (!array.status.empty()) {
    array.header.stamp = now();
    diag_pub_->publish(array);
  }
}

void SpeedPlannerNode::run_plan(const std_msgs::msg::Float64 & in) {
  r2d::RunGate::Scope run(gate_);
  if (!run) { return; }
  const auto params = params_.acquire();  // one snapshot for the whole execution (SPEC-12 §5)
  PlanResult r;
  if (!eval_plan(in, *params, state_, 0.0, 0.0, r)) {
    diag_.report(r2d::Code::ERR_RUN_101, "plan");  // preallocated ring: no allocation, no logging here
    return;
  }
  state_.last_speed = r.next_last_speed;  // step 5: commit
  {
    std_msgs::msg::String out{};  // value-initialised
    out.data = r.out__label_pub__data;
    pub_label_pub_->publish(out);
  }
  {
    std_msgs::msg::Float64 out{};  // value-initialised
    out.data = r.out__speed_pub__data;
    pub_speed_pub_->publish(out);
  }
}

}  // namespace planning
