// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
// The application: owns the ROS context, the node and the executor, and runs them. `main()` only
// creates it and calls `run()`.
#pragma once

#include <memory>

#include <rclcpp/rclcpp.hpp>

#include "counter_node/counter_node_node.hpp"
#include "counter_node/ros_binding.hpp"

namespace demo {

class CounterNodeApp {
 public:
  CounterNodeApp(int argc, char ** argv);
  CounterNodeApp(const CounterNodeApp &) = delete;
  CounterNodeApp & operator=(const CounterNodeApp &) = delete;

  // Spins until the context is shut down (for example by Ctrl-C). Returns the exit status.
  int run();

 private:
  // Initialises ROS first and shuts it down last, after the node and the executor are gone.
  struct RosContext {
    RosContext(int argc, char ** argv) { binding::init(argc, argv); }
    ~RosContext() { binding::shutdown(); }
    RosContext(const RosContext &) = delete;
    RosContext & operator=(const RosContext &) = delete;
  };

  RosContext context_;
  std::shared_ptr<CounterNode> node_;
  std::unique_ptr<rclcpp::Executor> executor_;
};

}  // namespace demo
