// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
// The ROS node. It only wires its parts together, in this construction order: the engine (the
// ROS-free core), the parameters, the interfaces (publishers, subscriptions, services, timers)
// and the diagnostics.
#pragma once

#include <rclcpp/rclcpp.hpp>

#include "counter_node/diagnostics.hpp"
#include "counter_node/engine.hpp"
#include "counter_node/interfaces.hpp"
#include "counter_node/parameters.hpp"

namespace demo {

class CounterNode : public rclcpp::Node {
 public:
  explicit CounterNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

 private:
  CounterNodeEngine engine_;
  CounterNodeParameters parameters_;
  CounterNodeInterfaces interfaces_;
  CounterNodeDiagnostics diagnostics_;
};

}  // namespace demo
