// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 74d678a0f620298d24714a0ad2502171823ee9880c1a05a398425dec8b452f56
#pragma once
#include <atomic>
#include <chrono>
#include <memory>
#include <string>
#include <vector>
#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/int64.hpp>
#include <std_srvs/srv/trigger.hpp>
#include "counter_node/pipelines.hpp"
#include "counter_node/runtime.hpp"

namespace demo {

class CounterNode : public rclcpp::Node {
public:
  explicit CounterNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

private:
  void declare_parameters();       // constructor only: declaration, no pipeline resources
  rcl_interfaces::msg::SetParametersResult on_set_parameters(const std::vector<rclcpp::Parameter> & updates);
  void create_interfaces();
  void drain_diagnostics();
  void run_reset(const std_srvs::srv::Trigger::Request & in, std_srvs::srv::Trigger::Response & res);
  void run_tick();

  r2d::SnapshotRing<Params, 3> params_;  // 3 = threads (1) + 2 (SPEC-12 §5)
  State state_;                                      // touched only through the callback group of the pipelines that use it (SPEC-12 §3)
  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
  OnSetParametersCallbackHandle::SharedPtr param_handle_;
  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::CallbackGroup::SharedPtr group_diagnostics_;
  rclcpp::Publisher<std_msgs::msg::Int64>::SharedPtr pub_count_pub_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr srv_reset_srv_;
  rclcpp::TimerBase::SharedPtr timer_tick_;
  std::atomic<bool> busy_tick_{false};
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr diag_pub_;
  rclcpp::TimerBase::SharedPtr diag_timer_;
  rclcpp::Clock::SharedPtr clock_diag_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
};

}  // namespace demo
