// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
// Publishes what the engine's diagnostics ring collected, on a timer of its own
// (SPEC-12 section 7).
#pragma once

#include <memory>

#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rclcpp/rclcpp.hpp>

#include "counter_node/engine.hpp"
#include "counter_node/interface_names.hpp"
#include "counter_node/ros_binding.hpp"

namespace demo {

class CounterNodeDiagnostics {
 public:
  CounterNodeDiagnostics(rclcpp::Node & node, CounterNodeEngine & engine);
  CounterNodeDiagnostics(const CounterNodeDiagnostics &) = delete;
  CounterNodeDiagnostics & operator=(const CounterNodeDiagnostics &) = delete;

 private:
  void drain();

  rclcpp::Node & node_;
  CounterNodeEngine & engine_;
  rclcpp::CallbackGroup::SharedPtr group_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr pub_;
  rclcpp::Clock::SharedPtr clock_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
  rclcpp::TimerBase::SharedPtr timer_;
};

}  // namespace demo
