// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
// The ROS-free core of the node. It owns the parameter snapshots, the state, the run gate and the
// diagnostics ring, and has one `run_<pipeline>` method per pipeline: evaluate, commit the state,
// return the outputs to publish. It never publishes: the adapters (interfaces.hpp,
// parameters.hpp, diagnostics.hpp) feed it and publish what it returns.
#pragma once

#include <optional>
#include <string>

#include "counter_node/interface_names.hpp"
#include "counter_node/pipelines.hpp"
#include "counter_node/runtime.hpp"

namespace demo {

class CounterNodeEngine {
 public:
  CounterNodeEngine() : params_(Params{}) {}
  CounterNodeEngine(const CounterNodeEngine &) = delete;
  CounterNodeEngine & operator=(const CounterNodeEngine &) = delete;

  // ---- parameters -----------------------------------------------------------------------------
  // Both validate. A rejected value is returned as the reason and nothing changes
  // (SPEC-07 section 3.1).

  std::optional<std::string> start(const Params & initial) {
    if (auto why = validate(initial)) {
      return why;
    }
    params_.publish([&](Params & slot) { slot = initial; });
    return std::nullopt;
  }

  Params parameters() { return *params_.acquire(); }

  std::optional<std::string> update(const Params & next) {
    if (auto why = validate(next)) {
      return why;
    }
    if (!params_.publish([&](Params & slot) { slot = next; })) {
      return std::string("parameter store busy, retry");
    }
    return std::nullopt;
  }

  // ---- run gate -------------------------------------------------------------------------------
  // Closed until `open()`. A pipeline runs only while its caller holds the `Scope` that `enter()`
  // returns, and the caller keeps it until it has published the result (SPEC-12 section 6).
  // Check it with `if (!run)`.

  void open() noexcept { gate_.open(); }

  r2d::RunGate::Scope enter() noexcept { return r2d::RunGate::Scope(gate_); }

  // ---- diagnostics ----------------------------------------------------------------------------
  // Any thread reports; one consumer drains (SPEC-12 section 7).

  void report(r2d::Code code, const char * who) noexcept { diag_.report(code, who); }

  template <class Emit>
  void drain_diagnostics(Emit && emit) {
    diag_.drain(emit);
  }

  // ---- pipelines ------------------------------------------------------------------------------
  // `In` is the trigger's message or request type. A pipeline returns nothing when a numeric
  // fault stopped it: the fault is reported as ERR_RUN_101 and nothing is committed.

  template <class In>
  std::optional<ResetResult> run_reset(const r2d::RunGate::Scope &, const In & in) {
    // One snapshot for the whole execution (SPEC-12 section 5).
    const auto params = params_.acquire();

    ResetResult r;
    if (!eval_reset(in, *params, state_, 0.0, 0.0, r)) {
      // A preallocated ring: no allocation and no logging here.
      diag_.report(r2d::Code::ERR_RUN_101, names::kPipelineReset);
      return std::nullopt;
    }

    // Step 5: commit.
    state_.count = r.next_count;

    return r;
  }

  std::optional<TickResult> run_tick(const r2d::RunGate::Scope &) {
    // One snapshot for the whole execution (SPEC-12 section 5).
    const auto params = params_.acquire();

    TickResult r;
    if (!eval_tick(*params, state_, 0.0, 0.0, r)) {
      // A preallocated ring: no allocation and no logging here.
      diag_.report(r2d::Code::ERR_RUN_101, names::kPipelineTick);
      return std::nullopt;
    }

    // Step 5: commit.
    state_.count = r.next_count;

    return r;
  }

 private:
  // One slot per thread (1), the current one and a free one (SPEC-12 section 5).
  r2d::SnapshotRing<Params, 3> params_;

  // Touched only through the callback group of the pipelines that use it (SPEC-12 section 3).
  State state_;

  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
};

}  // namespace demo
