// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
// The ROS side of the pipelines: creates the publishers, subscriptions, services and timers, and hands what arrives to the engine
// and what the engine returns to the publishers.
#pragma once
#include <atomic>
#include <chrono>
#include <memory>
#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/int64.hpp>
#include <std_srvs/srv/trigger.hpp>
#include "counter_node/engine.hpp"
#include "counter_node/interface_names.hpp"

namespace demo {

class CounterNodeInterfaces {
public:
  CounterNodeInterfaces(rclcpp::Node & node, CounterNodeEngine & engine);
  CounterNodeInterfaces(const CounterNodeInterfaces &) = delete;
  CounterNodeInterfaces & operator=(const CounterNodeInterfaces &) = delete;

  // Runs the startup pipelines once; the node calls it after it is operational (SPEC-02 section 7).
  void start();

private:
  void run_reset(const std_srvs::srv::Trigger::Request & in, std_srvs::srv::Trigger::Response & res);
  void run_tick();

  rclcpp::Node & node_;
  CounterNodeEngine & engine_;
  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::Publisher<std_msgs::msg::Int64>::SharedPtr pub_count_pub_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr srv_reset_srv_;
  rclcpp::TimerBase::SharedPtr timer_tick_;
  std::atomic<bool> busy_tick_{false};
};

}  // namespace demo
