// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
// Every name and number the manifest gives the node: topics, services, QoS depths, timer periods, parameter names and
// pipeline names. The rest of the generated code refers to these constants and repeats no such literal.
#pragma once
#include <cstddef>
#include <cstdint>

namespace demo::names {

inline constexpr char kNodeName[] = "counter_node";
inline constexpr char kNodeNamespace[] = "/demo";
inline constexpr char kDiagnosticsTopic[] = "/diagnostics";
inline constexpr std::size_t kDiagnosticsQosDepth = 10;
inline constexpr std::int64_t kDiagnosticsPeriodS = 1;
inline constexpr char kParametersWho[] = "parameters";
inline constexpr std::size_t kExecutorThreads = 1;
inline constexpr char kPubTopicCountPub[] = "/demo/count";
inline constexpr std::size_t kPubQosDepthCountPub = 10;
inline constexpr char kServiceNameResetSrv[] = "/demo/reset";
inline constexpr char kPipelineReset[] = "reset";
inline constexpr char kPipelineTick[] = "tick";
inline constexpr std::int64_t kPeriodMsTick = 500;
inline constexpr char kParamLimit[] = "limit";
inline constexpr char kParamStep[] = "step";

}  // namespace demo::names
