// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
// The ROS side of the parameters: declares them on the node (their values include launch-file and
// command-line overrides) and forwards every later update to the engine, which validates it
// (SPEC-07 section 3.1).
#pragma once

#include <vector>

#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>

#include "counter_node/engine.hpp"
#include "counter_node/interface_names.hpp"
#include "counter_node/ros_binding.hpp"

namespace demo {

class CounterNodeParameters {
 public:
  // Throws rclcpp::exceptions::InvalidParameterValueException when a starting value is invalid:
  // the node then refuses to start.
  CounterNodeParameters(rclcpp::Node & node, CounterNodeEngine & engine);
  CounterNodeParameters(const CounterNodeParameters &) = delete;
  CounterNodeParameters & operator=(const CounterNodeParameters &) = delete;

 private:
  rcl_interfaces::msg::SetParametersResult on_set(const std::vector<rclcpp::Parameter> & updates);

  CounterNodeEngine & engine_;
  binding::ParameterCallbackHandle handle_;
};

}  // namespace demo
