// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
// Parameters, state and the pipelines of the manifest as plain C++: no ROS dependency. Message
// types are template parameters.
#pragma once

#include <cmath>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include "counter_node/runtime.hpp"

namespace demo {

struct Params {
  std::int64_t limit{std::int64_t{10}};
  std::int64_t step{std::int64_t{1}};
};

struct State {
  std::int64_t count{std::int64_t{0}};
};

inline bool constraint_0(
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] bool & fault) {
  const bool n2 = (params.step <= params.limit);

  return n2;
}

// One validation function for the initial values and for every update, so both obey the same
// rules.
inline std::optional<std::string> validate([[maybe_unused]] const Params & p) {
  if (!(p.step >= std::int64_t{1})) {
    return std::string("'step' out of range [1, inf]");
  }

  {
    bool fault = false;
    const bool ok = constraint_0(p, fault);
    if (fault) {
      return std::string("parameter_constraints[0] faulted on the new values");
    }
    if (!ok) {
      return std::string("step must not exceed limit");
    }
  }

  return std::nullopt;
}

// Pipeline `reset` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and
// publishes.
struct ResetResult {
  std::int64_t next_count{};
  std::string out__res__message{};
  bool out__res__success{};
};

template <class In>
inline bool eval_reset(
    [[maybe_unused]] const In & in,
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] const State & state,
    [[maybe_unused]] double now_sec,
    [[maybe_unused]] double dt_sec,
    ResetResult & out) {
  bool fault = false;

  const std::int64_t n0 = std::int64_t{0};
  const std::string n1 = std::string("counter reset");
  const bool n2 = true;

  if (fault) {
    return false;
  }

  out.next_count = n0;
  out.out__res__message = n1;
  out.out__res__success = n2;
  return true;
}

// Pipeline `tick` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and
// publishes.
struct TickResult {
  std::int64_t next_count{};
  std::int64_t out__count_pub__data{};
};

inline bool eval_tick(
    [[maybe_unused]] const Params & params,
    [[maybe_unused]] const State & state,
    [[maybe_unused]] double now_sec,
    [[maybe_unused]] double dt_sec,
    TickResult & out) {
  bool fault = false;

  const std::int64_t v_next =
      ((r2d::wrap_add<std::int64_t>(state.count, params.step) >= params.limit)
          ? static_cast<std::int64_t>(std::int32_t{0})
          : r2d::wrap_add<std::int64_t>(state.count, params.step));

  if (fault) {
    return false;
  }

  out.next_count = v_next;
  out.out__count_pub__data = v_next;
  return true;
}

}  // namespace demo
