# Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
# IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
# `ros2 launch echo_node echo_node.launch.py`.
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        Node(package="echo_node", executable="echo_node", output="screen"),
    ])
