# Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
# IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
# Run it with `ros2 launch imu_filter_node imu_filter_node.launch.py`.
# It starts the node with the parameter file in config/.
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    share = get_package_share_directory("imu_filter_node")
    params = os.path.join(share, "config", "imu_filter_node.params.yaml")

    node = Node(
        package="imu_filter_node",
        executable="imu_filter_node",
        output="screen",
        parameters=[params],
    )
    return LaunchDescription([node])
