# Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
# IR hash: cf473c6f24952073b0ad5f7ea6769da29b35ab9137f76e035719b2da74a0dfe8
# Run it with `ros2 launch counter_node counter_node.launch.py`.
# It starts the node with the parameter file in config/.
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    share = get_package_share_directory("counter_node")
    params = os.path.join(share, "config", "counter_node.params.yaml")

    node = Node(
        package="counter_node",
        executable="counter_node",
        output="screen",
        parameters=[params],
    )
    return LaunchDescription([node])
