// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
// The application: owns the ROS context, the node and the executor, and runs them. `main()` only
// creates it and calls `run()`.
#pragma once

#include <memory>

#include <rclcpp/rclcpp.hpp>

#include "echo_node/echo_node_node.hpp"
#include "echo_node/ros_binding.hpp"

namespace demo {

class EchoNodeApp {
 public:
  EchoNodeApp(int argc, char ** argv);
  EchoNodeApp(const EchoNodeApp &) = delete;
  EchoNodeApp & operator=(const EchoNodeApp &) = delete;

  // Spins until the context is shut down (for example by Ctrl-C). Returns the exit status.
  int run();

 private:
  // Initialises ROS first and shuts it down last, after the node and the executor are gone.
  struct RosContext {
    RosContext(int argc, char ** argv) { binding::init(argc, argv); }
    ~RosContext() { binding::shutdown(); }
    RosContext(const RosContext &) = delete;
    RosContext & operator=(const RosContext &) = delete;
  };

  RosContext context_;
  std::shared_ptr<EchoNode> node_;
  std::unique_ptr<rclcpp::Executor> executor_;
};

}  // namespace demo
