// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
// Publishes what the engine's diagnostics ring collected, on a timer of its own
// (SPEC-12 section 7).
#pragma once

#include <memory>

#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rclcpp/rclcpp.hpp>

#include "echo_node/engine.hpp"
#include "echo_node/interface_names.hpp"
#include "echo_node/ros_binding.hpp"

namespace demo {

class EchoNodeDiagnostics {
 public:
  EchoNodeDiagnostics(rclcpp::Node & node, EchoNodeEngine & engine);
  EchoNodeDiagnostics(const EchoNodeDiagnostics &) = delete;
  EchoNodeDiagnostics & operator=(const EchoNodeDiagnostics &) = delete;

 private:
  void drain();
  void log(r2d::Code code, const char * who, std::size_t count);

  rclcpp::Node & node_;
  EchoNodeEngine & engine_;
  rclcpp::CallbackGroup::SharedPtr group_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr pub_;
  rclcpp::Clock::SharedPtr clock_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
  rclcpp::TimerBase::SharedPtr timer_;
};

}  // namespace demo
