// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 50a450c5459e7db9b034e65f253d4f18f6bfa624dd536c968d9e1303ff9003d1
#pragma once
#include <atomic>
#include <chrono>
#include <memory>
#include <string>
#include <vector>
#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/float64.hpp>
#include "echo_node/pipelines.hpp"
#include "echo_node/runtime.hpp"

namespace demo {

class EchoNode : public rclcpp::Node {
public:
  explicit EchoNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

private:
  void declare_parameters();       // constructor only: declaration, no pipeline resources
  rcl_interfaces::msg::SetParametersResult on_set_parameters(const std::vector<rclcpp::Parameter> & updates);
  void create_interfaces();
  void drain_diagnostics();
  void run_echo(const std_msgs::msg::Float64 & in);

  r2d::SnapshotRing<Params, 3> params_;  // 3 = threads (1) + 2 (SPEC-12 §5)
  State state_;                                      // touched only through the callback group of the pipelines that use it (SPEC-12 §3)
  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
  OnSetParametersCallbackHandle::SharedPtr param_handle_;
  rclcpp::CallbackGroup::SharedPtr group_pipeline_echo_;
  rclcpp::CallbackGroup::SharedPtr group_diagnostics_;
  rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr pub_out_pub_;
  rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr sub_in_sub_echo_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr diag_pub_;
  rclcpp::TimerBase::SharedPtr diag_timer_;
  rclcpp::Clock::SharedPtr clock_diag_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
};

}  // namespace demo
