// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
// The ROS node. It only wires its parts together, in this construction order: the engine (the
// ROS-free core), the parameters, the interfaces (publishers, subscriptions, services, timers)
// and the diagnostics.
#pragma once

#include <rclcpp/rclcpp.hpp>

#include "echo_node/diagnostics.hpp"
#include "echo_node/engine.hpp"
#include "echo_node/interfaces.hpp"
#include "echo_node/parameters.hpp"

namespace demo {

class EchoNode : public rclcpp::Node {
 public:
  explicit EchoNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

 private:
  EchoNodeEngine engine_;
  EchoNodeParameters parameters_;
  EchoNodeInterfaces interfaces_;
  EchoNodeDiagnostics diagnostics_;
};

}  // namespace demo
