// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
// The ROS side of the pipelines: creates the publishers, subscriptions, services and timers,
// hands what arrives to the engine and what the engine returns to the publishers.
#pragma once

#include <atomic>
#include <chrono>
#include <memory>

#include <rclcpp/rclcpp.hpp>

#include <std_msgs/msg/float64.hpp>

#include "echo_node/engine.hpp"
#include "echo_node/interface_names.hpp"
#include "echo_node/ros_binding.hpp"

namespace demo {

class EchoNodeInterfaces {
 public:
  EchoNodeInterfaces(rclcpp::Node & node, EchoNodeEngine & engine);
  EchoNodeInterfaces(const EchoNodeInterfaces &) = delete;
  EchoNodeInterfaces & operator=(const EchoNodeInterfaces &) = delete;

  // Runs the startup pipelines once. The node calls it when it is operational
  // (SPEC-02 section 7).
  void start();

 private:
  void run_echo(const std_msgs::msg::Float64 & in);

  rclcpp::Node & node_;
  EchoNodeEngine & engine_;

  rclcpp::CallbackGroup::SharedPtr group_pipeline_echo_;
  rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr pub_out_pub_;
  rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr sub_in_sub_echo_;
};

}  // namespace demo
