// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
// Every name and number the manifest gives the node: topics, services, QoS depths, timer periods,
// parameter names and pipeline names. The rest of the generated code refers to these constants
// and repeats no such literal.
#pragma once

#include <cstddef>
#include <cstdint>

namespace demo::names {

// The node
inline constexpr char kNodeName[] = "echo_node";
inline constexpr char kNodeNamespace[] = "/demo";
inline constexpr std::size_t kExecutorThreads = 1;

// Diagnostics
inline constexpr char kDiagnosticsTopic[] = "/diagnostics";
inline constexpr std::size_t kDiagnosticsQosDepth = 10;
inline constexpr std::int64_t kDiagnosticsPeriodS = 1;

// Publishers
inline constexpr char kPubTopicOutPub[] = "/demo/out";
inline constexpr std::size_t kPubQosDepthOutPub = 10;

// Subscribers
inline constexpr char kSubTopicInSub[] = "/demo/in";
inline constexpr std::size_t kSubQosDepthInSub = 10;

// Pipelines
inline constexpr char kPipelineEcho[] = "echo";

// Parameters
inline constexpr char kParametersWho[] = "parameters";

}  // namespace demo::names
