// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
// The ROS side of the parameters: declares them on the node (their values include launch-file and
// command-line overrides) and forwards every later update to the engine, which validates it
// (SPEC-07 section 3.1).
#pragma once

#include <vector>

#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>

#include "echo_node/engine.hpp"
#include "echo_node/interface_names.hpp"
#include "echo_node/ros_binding.hpp"

namespace demo {

class EchoNodeParameters {
 public:
  // Throws rclcpp::exceptions::InvalidParameterValueException when a starting value is invalid:
  // the node then refuses to start.
  EchoNodeParameters(rclcpp::Node & node, EchoNodeEngine & engine);
  EchoNodeParameters(const EchoNodeParameters &) = delete;
  EchoNodeParameters & operator=(const EchoNodeParameters &) = delete;

 private:
  rcl_interfaces::msg::SetParametersResult on_set(const std::vector<rclcpp::Parameter> & updates);

  EchoNodeEngine & engine_;
  binding::ParameterCallbackHandle handle_;
};

}  // namespace demo
