// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 50a450c5459e7db9b034e65f253d4f18f6bfa624dd536c968d9e1303ff9003d1
// Parameters, state and the pipelines of the manifest as plain C++: no ROS dependency. Message types are template parameters.
#pragma once
#include <cmath>
#include <cstdint>
#include <optional>
#include <regex>
#include <string>
#include <vector>
#include "echo_node/runtime.hpp"

namespace demo {

struct Params {
};

struct State {
};

// One validation function for the initial values and for every update, so both obey the same rules.
inline std::optional<std::string> validate([[maybe_unused]] const Params & p) {
  return std::nullopt;
}

// Pipeline `echo` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and publishes.
struct EchoResult {
  double out__out_pub__data{};
};

template <class In>
inline bool eval_echo([[maybe_unused]] const In & in, [[maybe_unused]] const Params & params, [[maybe_unused]] const State & state, [[maybe_unused]] double now_sec, [[maybe_unused]] double dt_sec, EchoResult & out) {
  bool fault = false;
  const double v_doubled = (in.data * 2.0);
  r2d::check_finite(v_doubled, fault);
  if (fault) return false;
  out.out__out_pub__data = v_doubled;
  return true;
}

}  // namespace demo
