// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
// The application: owns the ROS context, the node and the executor, and runs them. `main()` only creates it and calls `run()`.
#pragma once
#include <memory>
#include <rclcpp/rclcpp.hpp>
#include "imu_filter_node/imu_filter_node_node.hpp"

namespace sensors::chassis {

class ImuFilterNodeApp {
public:
  ImuFilterNodeApp(int argc, char ** argv);
  ImuFilterNodeApp(const ImuFilterNodeApp &) = delete;
  ImuFilterNodeApp & operator=(const ImuFilterNodeApp &) = delete;

  // Spins until the context is shut down (for example by Ctrl-C) and returns the process exit status.
  int run();

private:
  // Initialises ROS first and shuts it down last, after the node and the executor are gone.
  struct RosContext {
    RosContext(int argc, char ** argv) { rclcpp::init(argc, argv); }
    ~RosContext() { rclcpp::shutdown(); }
    RosContext(const RosContext &) = delete;
    RosContext & operator=(const RosContext &) = delete;
  };

  RosContext context_;
  std::shared_ptr<ImuFilterNode> node_;
  std::unique_ptr<rclcpp::Executor> executor_;
};

}  // namespace sensors::chassis
