// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
// Publishes what the engine's diagnostics ring collected, on a timer of its own (SPEC-12 section 7).
#pragma once
#include <rclcpp/rclcpp.hpp>
#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include "imu_filter_node/engine.hpp"
#include "imu_filter_node/interface_names.hpp"

namespace sensors::chassis {

class ImuFilterNodeDiagnostics {
public:
  ImuFilterNodeDiagnostics(rclcpp::Node & node, ImuFilterNodeEngine & engine);
  ImuFilterNodeDiagnostics(const ImuFilterNodeDiagnostics &) = delete;
  ImuFilterNodeDiagnostics & operator=(const ImuFilterNodeDiagnostics &) = delete;

private:
  void drain();

  rclcpp::Node & node_;
  ImuFilterNodeEngine & engine_;
  rclcpp::CallbackGroup::SharedPtr group_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr pub_;
  rclcpp::Clock::SharedPtr clock_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
  rclcpp::TimerBase::SharedPtr timer_;
};

}  // namespace sensors::chassis
