// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
// The ROS node: it only wires its parts together. The parts, in construction order: the engine (the ROS-free core), the
// parameters, the interfaces (publishers, subscriptions, services, timers) and the diagnostics.
#pragma once
#include <rclcpp/rclcpp.hpp>
#include "imu_filter_node/diagnostics.hpp"
#include "imu_filter_node/engine.hpp"
#include "imu_filter_node/interfaces.hpp"
#include "imu_filter_node/parameters.hpp"

namespace sensors::chassis {

class ImuFilterNode : public rclcpp::Node {
public:
  explicit ImuFilterNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

private:
  ImuFilterNodeEngine engine_;
  ImuFilterNodeParameters parameters_;
  ImuFilterNodeInterfaces interfaces_;
  ImuFilterNodeDiagnostics diagnostics_;
};

}  // namespace sensors::chassis
