// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 094879502fffce53eb3f35eddc7baf56862ffaebd0a972b4b396f96971b8ccdd
#pragma once
#include <atomic>
#include <chrono>
#include <memory>
#include <string>
#include <vector>
#include <diagnostic_msgs/msg/diagnostic_array.hpp>
#include <diagnostic_msgs/msg/diagnostic_status.hpp>
#include <diagnostic_msgs/msg/key_value.hpp>
#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/imu.hpp>
#include <std_msgs/msg/string.hpp>
#include "imu_filter_node/pipelines.hpp"
#include "imu_filter_node/runtime.hpp"

namespace sensors::chassis {

class ImuFilterNode : public rclcpp::Node {
public:
  explicit ImuFilterNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

private:
  void declare_parameters();       // constructor only: declaration, no pipeline resources
  rcl_interfaces::msg::SetParametersResult on_set_parameters(const std::vector<rclcpp::Parameter> & updates);
  void create_interfaces();
  void drain_diagnostics();
  void run_filter_imu(const sensor_msgs::msg::Imu & in);

  r2d::SnapshotRing<Params, 3> params_;  // 3 = threads (1) + 2 (SPEC-12 §5)
  State state_;                                      // touched only through the callback group of the pipelines that use it (SPEC-12 §3)
  r2d::RunGate gate_;
  r2d::DiagRing<> diag_;
  OnSetParametersCallbackHandle::SharedPtr param_handle_;
  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::CallbackGroup::SharedPtr group_diagnostics_;
  rclcpp::Publisher<sensor_msgs::msg::Imu>::SharedPtr pub_filtered_imu_pub_;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr pub_status_pub_;
  rclcpp::Subscription<sensor_msgs::msg::Imu>::SharedPtr sub_raw_imu_sub_filter_imu_;
  rclcpp::Publisher<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr diag_pub_;
  rclcpp::TimerBase::SharedPtr diag_timer_;
  rclcpp::Clock::SharedPtr clock_diag_{std::make_shared<rclcpp::Clock>(RCL_STEADY_TIME)};
};

}  // namespace sensors::chassis
