// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
// The ROS side of the pipelines: creates the publishers, subscriptions, services and timers,
// hands what arrives to the engine and what the engine returns to the publishers.
#pragma once

#include <memory>

#include <rclcpp/rclcpp.hpp>

#include <sensor_msgs/msg/imu.hpp>
#include <std_msgs/msg/string.hpp>

#include "imu_filter_node/engine.hpp"
#include "imu_filter_node/interface_names.hpp"
#include "imu_filter_node/ros_binding.hpp"

namespace sensors::chassis {

class ImuFilterNodeInterfaces {
 public:
  ImuFilterNodeInterfaces(rclcpp::Node & node, ImuFilterNodeEngine & engine);
  ImuFilterNodeInterfaces(const ImuFilterNodeInterfaces &) = delete;
  ImuFilterNodeInterfaces & operator=(const ImuFilterNodeInterfaces &) = delete;

  // Runs the startup pipelines once. The node calls it when it is operational
  // (SPEC-02 section 7).
  void start();

 private:
  void run_filter_imu(const sensor_msgs::msg::Imu & in);

  rclcpp::Node & node_;
  ImuFilterNodeEngine & engine_;

  rclcpp::CallbackGroup::SharedPtr group_state_domain_1_;
  rclcpp::Publisher<sensor_msgs::msg::Imu>::SharedPtr pub_filtered_imu_pub_;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr pub_status_pub_;
  rclcpp::Subscription<sensor_msgs::msg::Imu>::SharedPtr sub_raw_imu_sub_filter_imu_;
};

}  // namespace sensors::chassis
