// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
// Every name and number the manifest gives the node: topics, services, QoS depths, timer periods, parameter names and
// pipeline names. The rest of the generated code refers to these constants and repeats no such literal.
#pragma once
#include <cstddef>
#include <cstdint>

namespace sensors::chassis::names {

inline constexpr char kNodeName[] = "imu_filter_node";
inline constexpr char kNodeNamespace[] = "/sensors/chassis";
inline constexpr char kDiagnosticsTopic[] = "/diagnostics";
inline constexpr std::size_t kDiagnosticsQosDepth = 10;
inline constexpr std::int64_t kDiagnosticsPeriodS = 1;
inline constexpr char kParametersWho[] = "parameters";
inline constexpr std::size_t kExecutorThreads = 1;
inline constexpr char kPubTopicFilteredImuPub[] = "/sensor/imu/filtered";
inline constexpr std::size_t kPubQosDepthFilteredImuPub = 10;
inline constexpr char kPubTopicStatusPub[] = "/sensor/imu/status";
inline constexpr std::size_t kPubQosDepthStatusPub = 10;
inline constexpr char kSubTopicRawImuSub[] = "/sensor/imu/raw";
inline constexpr std::size_t kSubQosDepthRawImuSub = 5;
inline constexpr char kPipelineFilterImu[] = "filter_imu";
inline constexpr char kParamAlpha[] = "alpha";
inline constexpr char kParamMaxAccel[] = "max_accel";

}  // namespace sensors::chassis::names
