// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
// The ROS side of the parameters: declares them on the node (their values include launch-file and
// command-line overrides) and forwards every later update to the engine, which validates it
// (SPEC-07 section 3.1).
#pragma once

#include <vector>

#include <rcl_interfaces/msg/set_parameters_result.hpp>
#include <rclcpp/rclcpp.hpp>

#include "imu_filter_node/engine.hpp"
#include "imu_filter_node/interface_names.hpp"
#include "imu_filter_node/ros_binding.hpp"

namespace sensors::chassis {

class ImuFilterNodeParameters {
 public:
  // Throws rclcpp::exceptions::InvalidParameterValueException when a starting value is invalid:
  // the node then refuses to start.
  ImuFilterNodeParameters(rclcpp::Node & node, ImuFilterNodeEngine & engine);
  ImuFilterNodeParameters(const ImuFilterNodeParameters &) = delete;
  ImuFilterNodeParameters & operator=(const ImuFilterNodeParameters &) = delete;

 private:
  rcl_interfaces::msg::SetParametersResult on_set(const std::vector<rclcpp::Parameter> & updates);

  ImuFilterNodeEngine & engine_;
  binding::ParameterCallbackHandle handle_;
};

}  // namespace sensors::chassis
