// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 4cf0ab3bfb960372eb610d726663d31cc3398467f9943166b1a439e3df7b809d
// Parameters, state and the pipelines of the manifest as plain C++: no ROS dependency. Message types are template parameters.
#pragma once
#include <cmath>
#include <cstdint>
#include <optional>
#include <regex>
#include <string>
#include <vector>
#include "imu_filter_node/runtime.hpp"

namespace sensors::chassis {

struct Params {
  double alpha{0.85};
  double max_accel{20.0};
};

struct State {
  double prev_z{0.0};
};

// One validation function for the initial values and for every update, so both obey the same rules.
inline std::optional<std::string> validate([[maybe_unused]] const Params & p) {
  if (!(p.alpha >= 0.0 && p.alpha <= 1.0)) return std::string("'alpha' out of range [0.0, 1.0]");
  if (!(p.max_accel >= 0.0)) return std::string("'max_accel' out of range [0.0, inf]");
  return std::nullopt;
}

// Pipeline `filter_imu` (SPEC-02 §7 steps 1-4): evaluates and stages; the caller commits and publishes.
struct FilterImuResult {
  double next_prev_z{};
  std::string out__filtered_imu_pub__header__frame_id{};
  double out__filtered_imu_pub__linear_acceleration__z{};
  std::string out__status_pub__data{};
};

template <class In>
inline bool eval_filter_imu([[maybe_unused]] const In & in, [[maybe_unused]] const Params & params, [[maybe_unused]] const State & state, [[maybe_unused]] double now_sec, [[maybe_unused]] double dt_sec, FilterImuResult & out) {
  bool fault = false;
  const double v_z = r2d::low_pass(in.linear_acceleration.z, state.prev_z, params.alpha, fault);
  const bool v_over = (std::fabs(v_z) > params.max_accel);
  const std::string n7 = std::string(in.header.frame_id);
  const std::string n10 = (v_over ? std::string("OVERLIMIT") : std::string("OK"));
  r2d::check_finite(v_z, fault);
  if (fault) return false;
  out.next_prev_z = v_z;
  out.out__filtered_imu_pub__header__frame_id = n7;
  out.out__filtered_imu_pub__linear_acceleration__z = v_z;
  out.out__status_pub__data = n10;
  return true;
}

}  // namespace sensors::chassis
