# Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
# IR hash: b38a0259678c01ef7beb38231c50a262057d689c70f2a5d9fae3a503f0d5820b
# Run it with `ros2 launch gain_node gain_node.launch.py`.
# It starts the node with the parameter file in config/.
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    share = get_package_share_directory("gain_node")
    params = os.path.join(share, "config", "gain_node.params.yaml")

    node = Node(
        package="gain_node",
        executable="gain_node",
        output="screen",
        parameters=[params],
    )
    return LaunchDescription([node])
