// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
#include "echo_node/interfaces.hpp"

namespace demo {

// Everything is created here, before any callback can run (SPEC-03 §4.2). Each callback group is
// picked up with the node (`automatically_add_to_executor_with_node` defaults to true).
EchoNodeInterfaces::EchoNodeInterfaces(rclcpp::Node & node, EchoNodeEngine & engine)
    : node_(node), engine_(engine) {
  group_pipeline_echo_ = node_.create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);

  pub_out_pub_ = node_.create_publisher<std_msgs::msg::Float64>(
      names::kPubTopicOutPub,
      rclcpp::QoS(names::kPubQosDepthOutPub).reliable().durability_volatile());

  sub_in_sub_echo_ = binding::create_subscription<std_msgs::msg::Float64>(
      node_,
      names::kSubTopicInSub,
      rclcpp::QoS(names::kSubQosDepthInSub).reliable().durability_volatile(),
      [this](std_msgs::msg::Float64::ConstSharedPtr msg) { run_echo(*msg); },
      group_pipeline_echo_);
}

void EchoNodeInterfaces::start() {}

void EchoNodeInterfaces::run_echo(const std_msgs::msg::Float64 & in) {
  const auto run = engine_.enter();
  if (!run) {
    return;
  }

  const auto result = engine_.run_echo(run, in);
  if (!result) {
    // A numeric fault: the engine reported it (SPEC-02 section 7, step 6).
    return;
  }

  [[maybe_unused]] const auto & r = *result;

  {
    std_msgs::msg::Float64 out{};  // value-initialised
    out.data = r.out__out_pub__data;
    pub_out_pub_->publish(out);
  }
}

}  // namespace demo
