// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
#include <cstdio>
#include <cstdlib>
#include <exception>

#include "echo_node/app.hpp"

// A failure while starting or running (for example an invalid parameter value) ends the process
// with a message and a failure status, not with an abort.
int main(int argc, char ** argv) {
  try {
    return demo::EchoNodeApp(argc, argv).run();
  } catch (const std::exception & error) {
    std::fprintf(stderr, "%s: %s\n", demo::names::kNodeName, error.what());
  } catch (...) {
    std::fprintf(stderr, "%s: unknown error\n", demo::names::kNodeName);
  }
  return EXIT_FAILURE;
}
