// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: 50a450c5459e7db9b034e65f253d4f18f6bfa624dd536c968d9e1303ff9003d1
#include <memory>
#include <rclcpp/rclcpp.hpp>
#include "echo_node/echo_node_node.hpp"

int main(int argc, char ** argv) {
  rclcpp::init(argc, argv);
  auto node = std::make_shared<demo::EchoNode>();
  rclcpp::executors::SingleThreadedExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
