// Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
// IR hash: fb309b88a03a72e42a90ee7c1ec2c8d8ac9d10088a8c8981452fe04f71ab76ef
#include "echo_node/parameters.hpp"

#include <limits>
#include <string>
#include <utility>

namespace demo {

EchoNodeParameters::EchoNodeParameters(rclcpp::Node & node, EchoNodeEngine & engine) : engine_(engine) {
  Params initial;  // effective values include launch-file and command-line overrides
  if (auto why = engine_.start(initial)) {
    throw rclcpp::exceptions::InvalidParameterValueException(*why);  // refuse to start
  }
  handle_ = node.add_on_set_parameters_callback(
    [this](const std::vector<rclcpp::Parameter> & updates) { return on_set(updates); });
}

// Runs on the parameter-service thread, concurrently with the pipelines. It never touches state and never blocks a pipeline:
// the engine builds a whole new snapshot and swaps it in (SPEC-07 §3.1, SPEC-12 §5).
rcl_interfaces::msg::SetParametersResult EchoNodeParameters::on_set(const std::vector<rclcpp::Parameter> & updates) {
  auto reject = [this](std::string why) {
    engine_.report(r2d::Code::ERR_RUN_103, names::kParametersWho);
    rcl_interfaces::msg::SetParametersResult r;
    r.successful = false;
    r.reason = std::move(why);
    return r;
  };
  Params next = engine_.parameters();
  for (const auto & p : updates) {
    [[maybe_unused]] const std::string & name = p.get_name();
  }
  if (auto why = engine_.update(next)) return reject(*why);  // the whole batch is rejected, nothing is published
  rcl_interfaces::msg::SetParametersResult ok;
  ok.successful = true;
  return ok;
}

}  // namespace demo
