# Generated by nodesmith (SPEC-03). DO NOT EDIT DIRECTLY.
# IR hash: a6de20eed059bc5dd26c590e4a2a3a072505576f0499346f76bb5f5b68d5a332
# Run it with `ros2 launch speed_planner_node speed_planner_node.launch.py`.
# It starts the node with the parameter file in config/.
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    share = get_package_share_directory("speed_planner_node")
    params = os.path.join(share, "config", "speed_planner_node.params.yaml")

    node = Node(
        package="speed_planner_node",
        executable="speed_planner_node",
        output="screen",
        parameters=[params],
    )
    return LaunchDescription([node])
